Repository SuiteCRM/SuiteCRM, pull requests merged in 2018-04, with the labels that each got.

#5635 Fix #5624 Make all widget method signatures match their parents
  include/generic/SugarWidgets/SugarWidgetField.php
  include/generic/SugarWidgets/SugarWidgetFieldcurrency.php
  include/generic/SugarWidgets/SugarWidgetFielddate.php
  include/generic/SugarWidgets/SugarWidgetFielddatetime.php
  include/generic/SugarWidgets/SugarWidgetFieldenum.php
  include/generic/SugarWidgets/SugarWidgetFieldfloat.php
  include/generic/SugarWidgets/SugarWidgetFieldid.php
  include/generic/SugarWidgets/SugarWidgetFieldint.php
  include/generic/SugarWidgets/SugarWidgetFieldmultienum.php
  include/generic/SugarWidgets/SugarWidgetFieldname.php
  include/generic/SugarWidgets/SugarWidgetFieldparent_type.php
  include/generic/SugarWidgets/SugarWidgetFieldrelate.php
  include/generic/SugarWidgets/SugarWidgetFieldsingleenum.php
  include/generic/SugarWidgets/SugarWidgetFieldtext.php
  include/generic/SugarWidgets/SugarWidgetFieldtime.php
  include/generic/SugarWidgets/SugarWidgetFieldurl.php
  include/generic/SugarWidgets/SugarWidgetFielduser_name.php
  include/generic/SugarWidgets/SugarWidgetFieldvarchar.php
  include/generic/SugarWidgets/SugarWidgetSubPanelActivitiesStatusField.php
  include/generic/SugarWidgets/SugarWidgetSubPanelCloseButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelDelegatesSelectButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelDeleteButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php
  include/generic/SugarWidgets/SugarWidgetSubPanelEditButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelEditRoleButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelEmailLink.php
  include/generic/SugarWidgets/SugarWidgetSubPanelGetLatestButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelIcon.php
  include/generic/SugarWidgets/SugarWidgetSubPanelLoadSignedButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelManageAcceptancesButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelManageDelegatesButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelRelFieldEditButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonAccount.php
  include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonMeetings.php
  include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonProjects.php
  include/generic/SugarWidgets/SugarWidgetSubPanelSelectAllButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelSendInvitesButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelTopCreateCampaignLogEntryButton.php
  include/generic/SugarWidgets/SugarWidgetSubPanelTopMessage.php
Labels: Assessed, Ready to Merge

#5632 Removes a blank inherited function preventing the parent from running
  modules/Tasks/Task.php
Labels: Assessed, Ready to Merge

#4396 Missing space, put deprecated width and align in css
  ModuleInstall/PackageManager/tpls/ModuleLoaderListView.tpl
  include/Dashlets/DashletGenericDisplay.tpl
  include/ListView/ListViewDCMenu.tpl
  include/ListView/ListViewNoMassUpdate.tpl
  include/Popups/tpls/PopupGeneric.tpl
  modules/AM_ProjectTemplates/tpls/ListViewGeneric.tpl
  modules/Documents/tpls/view.extdoc.tpl
  modules/Home/UnifiedSearch.php
  modules/Import/tpls/listview.tpl
  themes/SuiteP/include/ListView/ListViewDCMenu.tpl
  themes/SuiteP/include/ListView/ListViewNoMassUpdate.tpl
  themes/SuiteP/include/Popups/tpls/PopupGeneric.tpl
Labels: Assessed

#5282 Stop required symbol from wrapping on edit form
  include/Smarty/plugins/block.minify.php
  themes/SuiteP/include/EditView/tab_panel_content.tpl
Labels: enhancement

#5535 Fixed #5515: Due date not showed anymore
  include/ListView/ListViewSubPanel.php
  modules/Calls/metadata/subpanels/ForHistory.php
  modules/Meetings/metadata/subpanels/ForHistory.php
  modules/Tasks/metadata/subpanels/ForHistory.php
Labels: Assessed

#4350 Fixed - #3558 Module Builder Fields
  modules/ModuleBuilder/tpls/MB.css
  modules/ModuleBuilder/tpls/MBModule/module.tpl
Labels: Assessed

#4273 Fixed #792 AOS Settings: Initial Invoice Number - add validation
  modules/Administration/AOSAdmin.php
Labels: Assessed

#5684 Fixed #5677 - Building new modules in builder do not work
  modules/ModuleBuilder/javascript/ModuleBuilder.js
Labels: Assessed

#5682 Fix/4021 template pdf format
  modules/AOS_PDF_Templates/formLetterPdf.php
Labels: Assessed

#5688 Fixed #5683: Can't assign user in Target list
  modules/ProspectLists/metadata/editviewdefs.php
Labels: Assessed

#5687 Fixed #5657: Multiple empty records are created in email_addresses table when access Users listview
  include/SugarObjects/templates/basic/Basic.php
  tests/unit/modules/Users/UserTest.php
Labels: Assessed

#5704 Fixed 5607 - Undefined variable $new_confirmed_opt_in
  include/SugarEmailAddress/SugarEmailAddress.php
Labels: Assessed

#5734 Fix/email failed permission check
  modules/Emails/EmailsController.php
Labels: Assessed

#5760 Turning off autocomplete in the login.tpl
  modules/Users/login.tpl
  themes/SuiteP/tpls/login.tpl
Labels: Assessed

#5713 Fix API error handling
  lib/API/v8/Controller/ApiController.php
Labels: Assessed

#5640 Fix/5639 subpanel compose email
  include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
  include/javascript/EmailsComposeViewModal.js
  include/javascript/jquery/jquery.sugarMenu.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
  modules/Emails/EmailUI.php
  modules/Emails/EmailsController.php
  tests/unit/modules/EmailMan/EmailManTest.php
  tests/unit/modules/Employees/EmployeeTest.php
  tests/unit/modules/Leads/LeadTest.php
  tests/unit/modules/Users/UserTest.php
Labels: Assessed

#5322 fix case email template
  modules/Emails/Email.php
Labels: Assessed

#3796 Fixed #3742 - Report Module - HTML contains invalid UTF-8 character(s)
  modules/AOR_Reports/controller.php
Labels: Assessed

#5770 Hotfix fixing PR #4485
  modules/EmailTemplates/EmailTemplate.php
Labels: Assessed

#3294 Fix 3275 - Remove extra delimiter at the end of the exported line
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#5750 Feature mocking
  composer.json
Labels: Assessed

#5735 Feature robo
  RoboFile.php
  composer.json
  include/StateCheckerConfig.php
  lib/Robo/Plugin/Commands/BuildCommands.php
  lib/Robo/Plugin/Commands/TestEnvironmentCommands.php
  lib/Robo/Traits/RoboTrait.php
  lib/Robo/config.php
  lib/Utility/OperatingSystem.php
  modules/AOR_Reports/controller.php
  modules/EmailTemplates/EmailTemplate.php
  tests/unit/lib/SuiteCRM/Utility/OperatingSystemTest.php
Labels: Assessed

#5786 Fixed #5639 - compose email link in activities subpanel
  include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Labels: Assessed

#5789 Fixing compose email link in activities subpanel in opportunities
  include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
Labels: Assessed

#5769 Fix/5731 password validation
  modules/Users/Changenewpassword.php
  modules/Users/Changenewpassword.tpl
  modules/Users/User.php
Labels: Assessed
