Repository SuiteCRM/SuiteCRM, pull requests merged in 2018-08, with the labels that each got.

#6188 Fixed #5856 - Multiple pages PDF from reports when Total of field is …
  modules/AOR_Reports/AOR_Report.php
  tests/unit/modules/AOR_Reports/AOR_ReportTest.php
Labels: Assessed

#6225 gcoop libre hotfix 6008 with no mem limit for composer install
  .travis.yml
  modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php
Labels: Assessed

#6220 FIX #6008 - Now Assigned-to column is not empty
  modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php
Labels: Assessed

#5577 Feature/collapsed subpanel row count
  include/SubPanel/SubPanelRowCounter.php
  include/SubPanel/SubPanelTiles.php
  modules/Users/Save.php
  modules/Users/UserViewHelper.php
  modules/Users/language/en_us.lang.php
  modules/Users/tpls/EditViewFooter.tpl
  tests/unit/include/SubPanel/SubPanelTest.php
  themes/SuiteP/css/suitep-base/panels.scss
  themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
Labels: Assessed, enhancement

#6237 FIX #6230 - Emails imported automatically in group inbound account are not marked as read
  modules/InboundEmail/InboundEmail.php
  modules/Schedulers/_AddJobsHere.php
Labels: Assessed

#6232 FIX #6231 - Now the query executed in getNewMessageIds has no WHERE harcoded
  modules/InboundEmail/AOPInboundEmail.php
  modules/InboundEmail/InboundEmail.php
  tests/unit/modules/InboundEmail/InboundEmailTest.php
Labels: Assessed

#6238 Fix #3864 - Deleted and recreated user can't login with system generated password
  modules/Users/User.php
Labels: Assessed

#6134 Fix #6133 - Contact popup of AOS_Contracts doesn't filter by account
  modules/AOS_Contracts/metadata/editviewdefs.php
Labels: Assessed

#5842 Do not get the cached version for newly created beans from Factory
  data/BeanFactory.php
  modules/AOW_Actions/actions/templateParser.php
Labels: Assessed

#5651 Fix/email quick create
  modules/Emails/EmailsController.php
  modules/Emails/include/DetailView/quickCreateModal.js
  modules/Emails/language/en_us.lang.php
  modules/Emails/metadata/detailviewdefs.php
Labels: Assessed, enhancement

#5821 Fix/5794 listview column filter
  modules/MySettings/StoreQuery.php
Labels: Assessed, needs tests

#6246 Fix merge fields not populating with the bean values
  jssource/src_files/modules/MergeRecords/Merge.js
  modules/MergeRecords/Merge.js
Labels: Assessed

#5729 Update overridden save functions to match parent return type
  modules/AM_ProjectTemplates/AM_ProjectTemplates.php
  modules/AOR_Reports/AOR_Report.php
  modules/AOR_Scheduled_Reports/AOR_Scheduled_Reports.php
  modules/AOS_Contracts/AOS_Contracts.php
  modules/AOS_Invoices/AOS_Invoices.php
  modules/AOS_Line_Item_Groups/AOS_Line_Item_Groups.php
  modules/AOS_Product_Categories/AOS_Product_Categories.php
  modules/AOS_Products/AOS_Products.php
  modules/AOS_Products_Quotes/AOS_Products_Quotes.php
  modules/AOS_Quotes/AOS_Quotes.php
  modules/AOW_WorkFlow/AOW_WorkFlow.php
  modules/CampaignTrackers/CampaignTracker.php
  modules/OAuthTokens/OAuthToken.php
  modules/Project/Project.php
Labels: Assessed

#5892 Fix bug on AOW_Actions relate fields
  modules/AOW_Actions/actions/actionComputeField.php
Labels: Assessed

#6268 Do not show img tag with same src attribute if an image field is empty
  include/SugarFields/Fields/Image/DetailView.tpl
Labels: Assessed

#6248 Fixed #6244 - 7.8.20LTS AOR_Report fails using a date parameter
  modules/AOR_Reports/AOR_Report.js
Labels: Assessed
