Repository SuiteCRM/SuiteCRM, pull requests merged in 2018-12, with the labels that each got.

#3649 Make sure deleted users are not used when validating users
  modules/Users/User.php
Labels: Assessed

#6565 fixes google calender language formatting
  modules/Administration/language/en_us.lang.php
Labels: Assessed

#6573 FIX #6568 - Change minimun and recommended PHP
  php_version.php
Labels: Community Contribution

#6260 testing email related functions
  .travis.yml
  include/Imap.php
  include/ImapInterface.php
  include/StateCheckerConfig.php
  modules/InboundEmail/InboundEmail.php
  tests/_support/Step/Acceptance/EmailManTester.php
  tests/acceptance/modules/Campaigns/CampaignsCest.php
  tests/acceptance/modules/EmailMan/EmailManCest.php
  tests/install/UserWizardCest.php
  tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php
  travis.php.ini
Labels: Assessed

#6590 Insert images in Email Templates with tinyMCE
  include/SuiteEditor/SuiteEditorConnector.php
Labels: Community Contribution

#6497 Fixed 6472 - Fix wrong image sizes for email templates in the campaign wizard
  modules/Campaigns/WizardMarketing.html
Labels: Community Contribution

#6550 FIX #6549 - Add missing surveys_campaigns relationship
  modules/Campaigns/vardefs.php
  modules/Surveys/vardefs.php
Labels: Community Contribution

#6597 AOR Report Export CSV was giving incorrect data when using apostrophe (') into any field
  modules/AOR_Reports/AOR_Report.php
Labels: Community Contribution

#6580 Fix #6579 - Calendar daily repeat end by
  modules/Calendar/CalendarUtils.php
Labels: Assessed

#3846 partial fix for issue of logic for default value
  include/SugarFields/Fields/Base/SugarFieldBase.php
Labels: Assessed

#6530 Manage subscriptions: Fix unsubscribed users showing up as subscribed sometimes
  modules/Campaigns/utils.php
Labels: Assessed, Community Contribution

#6411 Fixed #5783 - The table header with geocoded objects is not visible
  modules/jjwg_Maps/controller.php
  modules/jjwg_Maps/language/en_us.lang.php
  modules/jjwg_Maps/views/view.geocoded_counts.php
Labels: Assessed

#6302 Fixed installWizard styling - check writable module
  install/ready.php
Labels: Assessed

#6493 Definition of Favorites and Trackers Beans in Sugar View
  include/MVC/View/SugarView.php
Labels: Assessed

#6613 Fixed #6570 -Case description not saving when AJAX is disabled
  include/SugarTinyMCE.php
  modules/Cases/views/view.edit.php
Labels: Assessed

#6460 HotFix for Bug #2741
  include/utils.php
Labels: Assessed, Community Contribution

#5134 Fix For #1866 Display module by alphabetical order
  include/language/en_us.lang.php
Labels: Assessed, Enhancement

#6612 Fixed #6611 -
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
Labels: Assessed

#4311 Fixed #3083 - Calendar pop up windows are going under MENU bar
  themes/SuiteP/css/navbar.scss
Labels: Assessed

#4275 Fixed #583 Navigation module highlighting added
  themes/SuiteR/css/navhighlight.css
  themes/SuiteR/js/navhighlight.js
  themes/SuiteR/tpls/_head.tpl
  themes/SuiteR/tpls/_headerModuleList.tpl
Labels: Assessed

#2384 Fixed #163 - Pagination bar in Emails
  modules/Emails/EmailUI.css
  themes/Suite7/css/yui.css
  themes/SuiteP/css/yui.scss
  themes/SuiteR/css/yui.css
Labels: Assessed

#6378 Fixed #5948 - 7.8.18 Content Field on Campaign module can't be edited…
  modules/Campaigns/vardefs.php
Labels: Assessed

#5454 Fixed #2400 - Language manifest is duplicated and overwritten on each…
  modules/Administration/UpgradeWizard_prepare.php
Labels: Assessed

#6517 Fixed #6516 - (filler) elements in layouts are removed by gridlayout parser
  modules/ModuleBuilder/parsers/views/GridLayoutMetaDataParser.php
Labels: Assessed, Community Contribution

#6633 Fixed #5509 - [language] New label 'FOR_AMOUNT' in activity stream for opportunity
  modules/Opportunities/SugarFeeds/OppFeed.php
  modules/SugarFeed/language/en_us.lang.php
Labels: Assessed

#6449 Fixed #6414 - Bug in modules/Schedulers/_AddJobsHere.php
  modules/Schedulers/_AddJobsHere.php
Labels: Assessed, Community Contribution

#6004 Fix round up for cases where there is an increase in integral part.
  modules/AOS_Products_Quotes/line_items.js
  tests/acceptance/modules/Invoices/InvoicesCest.php
Labels: Community Contribution

#3008 Fix #3006 Now we can have module vardefs definitions or custom data in the DOM
  include/MVC/View/SugarView.php
Labels: Community Contribution, Enhancement

#4326 Fixed #994 - Address Translation
  install/install_utils.php
  modules/Administration/UpgradeAccess.php
Labels: Assessed

#6488 Fixed #6487 - opt-in: use the DB time for writing confirm_opt_in_*date
  include/SugarEmailAddress/SugarEmailAddress.php
  modules/Campaigns/WebToPersonCapture.php
  modules/EmailMan/EmailManDelivery.php
  modules/Emails/Email.php
Labels: Community Contribution

#2930 Fixed #707 - added conditional statement to check if action is not clone
  modules/ModuleBuilder/javascript/ModuleBuilder.js
Labels: Assessed, In Review

#6609 Fixed #6594 - Calendar doesn't update visually when NOT using "Shared Calendar Separate"
  jssource/src_files/modules/Calendar/Cal.js
  modules/Calendar/Cal.js
Labels: Assessed, Community Contribution

#6518 Fixed #2928 Fixed #341 - clear Zend OPcache when writing files
  include/SugarCache/SugarCache.php
  include/utils/file_utils.php
  include/utils/sugar_file_utils.php
Labels: Assessed, Community Contribution

#5894 Feature/massupdate extendable custom
  include/ListView/ListView.php
  include/ListView/ListViewDisplay.php
  include/MVC/Controller/SugarController.php
  include/Popups/PopupSmarty.php
  include/utils.php
  modules/AOS_PDF_Templates/formLetterPdf.php
  modules/ProspectLists/TargetListUpdate.php
Labels: Assessed, Enhancement

#6687 Minor grammar fixes to log entry
  modules/Emails/views/view.compose.php
Labels: Assessed, Community Contribution

#6649 FIX #6648 - We add a task in RoboFile.php for cleaning cache directory
  RoboFile.php
  lib/Robo/Plugin/Commands/CleanCacheCommands.php
Labels: Assessed, Community Contribution

#6671 FIX #6651 - Added LBL_CHECKMARK to SecurityGruop language
  modules/SecurityGroups/language/en_us.lang.php
Labels: Assessed, Community Contribution

#6693 Hotfix php error on uw page
  include/utils.php
  modules/InboundEmail/EditView.php
  modules/UpgradeWizard/uw_utils.php
Labels: Assessed

#6586 Fix an erroneously-commented return statement.
  include/utils.php
Labels: Assessed, Community Contribution
