Repository SuiteCRM/SuiteCRM, pull requests merged in 2018-02, with the labels that each got.

#5151 Fix #5115 Don't show qtip for new records
  jssource/src_files/modules/Calendar/Cal.js
  modules/Calendar/Cal.js
Labels: Assessed

#5182 Add Oauth2 Clients to admin
  lib/API/OAuth2/Middleware/ResourceServer.php
Labels: Assessed

#5172 Fix Return module issues
  modules/Campaigns/metadata/detailviewdefs.php
Labels: Assessed

#5142 quickfix for notification
  modules/Reminders/Reminder.php
  modules/Reminders/vardefs.php
Labels: Assessed

#5192 Fix Email bulk action in the list view
  include/ListView/ListViewDisplay.php
  modules/Emails/EmailUI.php
Labels: Assessed

#5194 Preventing 2 factor authentication from resending lots of codes
  modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
  modules/Users/authentication/SugarAuthenticate/SugarAuthenticateUser.php
Labels: Assessed

#5184 Feature/gdpr mass update and search opt in
  include/MVC/View/views/view.list.php
  include/MassUpdate.php
  include/OutboundEmail/OutboundEmail.php
  include/SugarEmailAddress/SugarEmailAddress.php
  include/SugarFields/Fields/Datetimecombo/Datetimecombo.js
  include/SugarObjects/templates/basic/Basic.php
  include/javascript/alerts.js
  include/javascript/sugar_3.js
  include/language/en_us.lang.php
  include/utils.php
  metadata/email_addressesMetaData.php
  modules/Accounts/metadata/SearchFields.php
  modules/Accounts/metadata/searchdefs.php
  modules/Administration/Administration.php
  modules/Campaigns/WebToLeadFormBuilder.php
  modules/Campaigns/language/en_us.lang.php
  modules/Configurator/Configurator.php
  modules/Contacts/metadata/SearchFields.php
  modules/Contacts/metadata/searchdefs.php
  modules/EmailMan/controller.php
  modules/EmailMarketing/EmailMarketing.php
  modules/Emails/EmailUI.php
  modules/Leads/metadata/SearchFields.php
  modules/Leads/metadata/searchdefs.php
  modules/Prospects/metadata/SearchFields.php
  modules/Prospects/metadata/searchdefs.php
  tests/unit/modules/EmailMan/EmailManTest.php
  tests/unit/modules/Employees/EmployeeTest.php
  tests/unit/modules/Leads/LeadTest.php
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/forms.scss
  themes/default/js/style.js
Labels: Assessed

#5196 Adding not opted in feature to Web To Person
  include/SugarEmailAddress/SugarEmailAddress.php
  modules/Campaigns/WebToLeadFormBuilderOptInCheckbox.tpl
  modules/Campaigns/WebToPersonCapture.php
  tests/unit/include/SugarEmailAddress/SugarEmailAddressTest.php
Labels: Assessed

#5078 Fixed #2341 - In Campaign view status page, row out of box
  modules/Campaigns/TrackDetailView.tpl
Labels: Assessed

#2272 Fixed #1433 - Removed duplicate name Polar Chart.
  include/language/en_us.lang.php
  modules/AOR_Charts/AOR_Chart.php
Labels: Assessed

#3443 loadUserOnLogin compatible with SugarAuthenticateUser::authenticateUser
  modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
Labels: Assessed, LTS, Ready to Merge

#5162 Fix/home page php notices
  include/Dashlets/Dashlet.php
  include/ListView/ListViewSmarty.php
  modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php
  modules/Accounts/Dashlets/MyAccountsDashlet/MyAccountsDashlet.php
  modules/Calls/Dashlets/MyCallsDashlet/MyCallsDashlet.php
  modules/Meetings/Dashlets/MyMeetingsDashlet/MyMeetingsDashlet.php
  modules/Opportunities/Dashlets/MyOpportunitiesDashlet/MyOpportunitiesDashlet.php
  modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
Labels: Assessed, Review

#5158 Fix/4247 saml password checkbox
  modules/Administration/PasswordManager.php
  modules/Administration/PasswordManager.tpl
Labels: Assessed

#5138 Fix/5130 import contact campaign
  modules/Contacts/Contact.php
Labels: Assessed

#5077 Fix #5076 Smtp full log
  include/SugarPHPMailer.php
  include/language/en_us.lang.php
  modules/Emails/Email.php
  modules/Emails/javascript/ajax.js
  modules/OutboundEmailAccounts/OutboundEmailAccounts.php
Labels: enhancement

#5220 Update method for API test suite
  tests/_support/Helper/PhpBrowserDriverHelper.php
Labels: Assessed

#5221 Fix/5175 style language
  include/SugarTheme/SugarThemeRegistry.php
Labels: Assessed, Ready to Merge

#5222 Calendar dashlet lbl
  modules/Home/language/en_us.lang.php
Labels: Ready to Merge

#5225 Fixing htaccess file to prepend new rules instead of append
  modules/Administration/UpgradeAccess.php
Labels: Ready to Merge

#4296 Fixed #2406 - css issue
  modules/AOR_Reports/tpls/EditViewFooter.tpl
Labels: Assessed

#5236 Fix PHP Strict Standards SugarView::init() in ModuleBuilder/views/view.property.php
  modules/ModuleBuilder/views/view.property.php
Labels: Assessed

#5216 Removing commented language string
  install/language/en_us.lang.php
  modules/Configurator/language/en_us.lang.php
Labels: Assessed

#5293 Fix opt in label in contacts filtering.
  include/language/en_us.lang.php
Labels: Assessed

#5323 Remove word "error" from a debug message
  data/SugarBean.php
Labels: Assessed

#5333 Fix #5327 Subject broken in Notes detail view
  include/SugarObjects/templates/file/File.php
Labels: Assessed

#5332 Fix #5317 Report ordering by date field
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#5362 htaccess generate after upgrade
  modules/UpgradeWizard/end.php
Labels: Assessed

#5365 htaccess generate after upgrade
  modules/UpgradeWizard/end.php
Labels: Assessed
