Repository SuiteCRM/SuiteCRM, pull requests merged in 2018-07, with the labels that each got.

#6098 Wrong link of roadmap
  README.md
Labels: Assessed

#6100 disabling group relationship for regular users (into 7.8.x)
  include/generic/Save2.php
  modules/SecurityGroups/SaveSecurityGroupUserRelationship.php
Labels: Assessed

#6115 Hotfix unit tests
  .travis.yml
  include/StateChecker.php
  include/Sugar_Smarty.php
  modules/AOR_Reports/AOR_Report.php
  modules/Audit/Audit.php
  modules/Audit/Popup_picker.php
  tests/bootstrap.php
  tests/phpunit.xml
  tests/unit/include/MVC/View/SugarViewTest.php
  tests/unit/lib/SuiteCRM/Utility/CurrentLanguageTest.php
  tests/unit/modules/AOR_Reports/AOR_ReportTest.php
  tests/unit/modules/Audit/PopupPickerTest.php
  tests/unit/modules/Currencies/CurrencyTest.php
Labels: Assessed

#5862 Fix test codecoverage
  composer.json
  lib/Robo/Plugin/Commands/CodeCoverageCommands.php
  tests/unit/lib/SuiteCRM/Robo/Commands/CodeCoverageCommandsTest.php
Labels: Assessed

#6065 Clarify a language string
  modules/Administration/language/en_us.lang.php
Labels: Assessed, LTS, Ready to Merge

#5485 Fixed #5343 - Mismatch between Security Groups and Security Suite names in Administration
  include/language/en_us.lang.php
  modules/SecurityGroups/language/en_us.lang.php
Labels: Assessed

#5471 Fixed #5468 - Usage of the word DROP [Language issue]
  modules/AOR_Reports/language/en_us.lang.php
  modules/AOR_Reports/tpls/EditViewFooter.tpl
Labels: Assessed

#6104 Fix Undefined variable
  service/v4/SugarWebServiceUtilv4.php
Labels: Assessed

#6033 Fix #5918 Activity Stream elapsed time calculation
  modules/SugarFeed/SugarFeed.php
  tests/unit/modules/SugarFeed/SugarFeedTest.php
Labels: Assessed

#2302 Fixed #2172 - Inline edit issue if you click on pencil icon - revised…
  include/InlineEditing/InlineEditing.php
  include/InlineEditing/inlineEditing.js
  tests/acceptance/modules/Accounts/AccountsCest.php
Labels: Assessed

#6109 Fix issue #6107 while updating cases using the html editor that it only sav…
  modules/AOP_Case_Updates/AOP_Case_Updates.php
Labels: Assessed

#6167 Strpos may return 0 when a match is found
  modules/AOS_PDF_Templates/templateParser.php
Labels: Assessed

#6160 Fix activities subpanel style
  include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Labels: Assessed

#6155 Update mikey179/vfsStream requirement to 1.6.*
  composer.json
Labels: Assessed

#5144 Fixed PHP notice
  modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
Labels: Assessed

#5476 Fixed #4920 - SugarFields Address language files for View.tpl
  include/SugarFields/Fields/Address/DetailView.tpl
  include/SugarFields/Fields/Address/en_us.DetailView.tpl
Labels: Assessed

#6042 Corrects repeated reference.
  modules/Contacts/metadata/listviewdefs.php
Labels: Assessed

#6157 Add composer.lock
  .gitignore
  composer.lock
Labels: Assessed

#6158 Add composer.lock 7.8.x
  composer.lock
Labels: Assessed

#6175 Fix faulty logic causing EmailMarketing not loading properly
  modules/Campaigns/WizardMarketing.php
Labels: Assessed

#4304 Fixed #2783 - In the calendar dashlet, right / left week icons are not visible
  themes/SuiteP/modules/Calendar/tpls/header.tpl
Labels: Assessed

#4344 Make Business Hours less mysterious
  modules/Administration/BusinessHours.tpl
  modules/Administration/language/en_us.lang.php
Labels: Assessed, LTS

#6127 #6126 fix(Change-log) - decode prev value before compare
  include/database/DBManager.php
Labels: LTS
