Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-11, with the labels that each got.

#8139 FIXED #8134 - Logo not in left-hand corner anymore
  install/language/en_us.lang.php
  modules/Configurator/language/en_us.lang.php
Labels: Assessed

#8158 Updating FPEvent unit test to use correct array.
  tests/unit/phpunit/modules/FP_events/FP_eventsTest.php
Labels: Assessed

#7580 export: Update export_excel_compatible to work with all Excel versions
  export.php
  include/Localization/Localization.php
  include/export_utils.php
  modules/AOR_Reports/AOR_Report.php
  tests/unit/phpunit/include/Localization/LocalizationTest.php
Labels: Assessed, Community Contribution

#8176 Fix #8173 - Workflow actions missing in edit and detail view
  modules/AOW_Actions/actionLines.php
Labels: Assessed

#8161 Fix a PHP warning in Meeting.php.
  modules/Meetings/Meeting.php
Labels: Assessed

#8181 Fix for Issue #7305 hotfix-7.10.x branch
  modules/AOR_Scheduled_Reports/AOR_Scheduled_Reports.php
Labels: Assessed

#8186 Removed unnecessary JSSource files
  jssource/src_files/include/SugarCharts/Jit/js/sugarCharts.js
  jssource/src_files/include/SugarEmailAddress/SugarEmailAddressLegacy.js
  jssource/src_files/modules/Home/about.js
Labels: Assessed

#8189 Fix/email template
  modules/FP_events/FP_events.php
  tests/unit/phpunit/modules/FP_events/FP_eventsTest.php
Labels: Assessed

#8236 Update the Travis Code Coverage job.
  .travis.yml
  composer.json
  composer.lock
Labels: Assessed

#8253 Remove some old code referencing PHP 5.3.
  include/TimeDate.php
  modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
  modules/iCals/iCal.php
Labels: Assessed

#8252 Deprecate various utils functions that are unused.
  include/utils.php
Labels: Assessed

#8235 Clean up misc unit tests
  tests/unit/phpunit/modules/EmailMarketing/EmailMarketingTest.php
  tests/unit/phpunit/modules/Employees/EmployeeTest.php
  tests/unit/phpunit/modules/Groups/GroupTest.php
  tests/unit/phpunit/modules/Roles/RoleTest.php
  tests/unit/phpunit/modules/UserPreferences/UserPreferenceTest.php
  tests/unit/phpunit/modules/Users/UserTest.php
  tests/unit/phpunit/modules/jjwg_Address_Cache/jjwg_Address_CacheTest.php
Labels: Assessed

#8234 Add tests for check_php_version.
  include/utils.php
  tests/unit/phpunit/include/UtilsTest.php
Labels: Assessed

#8231 Clean up include/ tests
  tests/unit/phpunit/data/SugarBeanTest.php
  tests/unit/phpunit/include/MVC/SugarApplicationTest.php
  tests/unit/phpunit/include/MVC/View/SugarViewTest.php
  tests/unit/phpunit/include/MVC/View/ViewFactoryTest.php
  tests/unit/phpunit/include/MVC/View/views/view.classicTest.php
  tests/unit/phpunit/include/MVC/View/views/view.htmlTest.php
  tests/unit/phpunit/include/MVC/View/views/view.importvcardsaveTest.php
  tests/unit/phpunit/include/MVC/View/views/view.jsonTest.php
  tests/unit/phpunit/include/MVC/View/views/view.listTest.php
  tests/unit/phpunit/include/MVC/View/views/view.metadataTest.php
  tests/unit/phpunit/include/MVC/View/views/view.modulelistmenuTest.php
  tests/unit/phpunit/include/MVC/View/views/view.multieditTest.php
  tests/unit/phpunit/include/MVC/View/views/view.noaccessTest.php
  tests/unit/phpunit/include/MVC/View/views/view.popupTest.php
  tests/unit/phpunit/include/MVC/View/views/view.quickTest.php
  tests/unit/phpunit/include/MVC/View/views/view.quickcreateTest.php
  tests/unit/phpunit/include/MVC/View/views/view.quickeditTest.php
  tests/unit/phpunit/include/MVC/View/views/view.sugarpdfTest.php
  tests/unit/phpunit/include/MVC/View/views/view.vcardTest.php
  tests/unit/phpunit/include/MVC/View/views/view.xmlTest.php
  tests/unit/phpunit/include/SugarEmailAddress/SugarEmailAddressTest.php
  tests/unit/phpunit/include/UtilsTest.php
  tests/unit/phpunit/include/utils/LogicHookTest.php
  tests/unit/phpunit/include/utils/activityUtilsTest.php
  tests/unit/phpunit/include/utils/arrayUtilsTest.php
  tests/unit/phpunit/include/utils/autoloaderTest.php
  tests/unit/phpunit/include/utils/dbUtilsTest.php
  tests/unit/phpunit/include/utils/encryptionUtilsTest.php
  tests/unit/phpunit/include/utils/layoutUtilsTest.php
  tests/unit/phpunit/include/utils/mvcUtilsTest.php
  tests/unit/phpunit/include/utils/phpZipUtilsTest.php
Labels: Assessed

#8218 Remove deprecated functions from utils.php.
  include/utils.php
Labels: Assessed

#8217 Remove the deprecated load_menu() function in utils.php
  include/utils.php
Labels: Assessed

#8216 Add a PHPDoc comment and test to unencodeMultienum()
  include/utils.php
  tests/unit/phpunit/include/UtilsTest.php
Labels: Assessed

#8156 tests: throw an error in case exit() is called during testing
  include/utils.php
Labels: Community Contribution

#8258 Fix "!" in pQuery and add tests
  include/database/DBManager.php
  tests/unit/phpunit/include/database/DBManagerTest.php
Labels: Assessed

#8249 Add unit tests for is_admin() function.
  tests/unit/phpunit/include/UtilsTest.php
Labels: Assessed

#8296 A few more little fixes for the formatting in the test suite.
  tests/unit/phpunit/data/SugarBeanTest.php
  tests/unit/phpunit/include/ErrorMessageTest.php
  tests/unit/phpunit/include/MVC/SugarApplicationTest.php
  tests/unit/phpunit/include/MVC/View/SugarViewTest.php
  tests/unit/phpunit/include/MVC/View/views/view.metadataTest.php
  tests/unit/phpunit/include/MVC/View/views/view.popupTest.php
  tests/unit/phpunit/include/MVC/View/views/view.serializedTest.php
  tests/unit/phpunit/include/MVC/View/views/view.sugarpdfTest.php
  tests/unit/phpunit/include/MVC/View/views/view.vcardTest.php
  tests/unit/phpunit/include/MVC/View/views/view.xmlTest.php
  tests/unit/phpunit/include/database/DBManagerTest.php
  tests/unit/phpunit/include/utils/LogicHookTest.php
  tests/unit/phpunit/include/utils/arrayUtilsTest.php
  tests/unit/phpunit/include/utils/layoutUtilsTest.php
  tests/unit/phpunit/include/utils/logicUtilsTest.php
  tests/unit/phpunit/include/utils/phpZipUtilsTest.php
  tests/unit/phpunit/include/utils/sugarFileUtilsTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/CurrentLanguageTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/ModuleLanguageTest.php
  tests/unit/phpunit/modules/AOR_Fields/AOR_FieldTest.php
  tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
  tests/unit/phpunit/modules/AOR_Scheduled_Reports/AOR_Scheduled_ReportsTest.php
  tests/unit/phpunit/modules/AOW_Actions/AOW_ActionTest.php
  tests/unit/phpunit/modules/Administration/AdministrationTest.php
  tests/unit/phpunit/modules/Alerts/AlertTest.php
  tests/unit/phpunit/modules/Bugs/BugTest.php
  tests/unit/phpunit/modules/Calls/CallTest.php
  tests/unit/phpunit/modules/CampaignLog/CampaignLogTest.php
  tests/unit/phpunit/modules/CampaignTrackers/CampaignTrackerTest.php
  tests/unit/phpunit/modules/Documents/DocumentTest.php
  tests/unit/phpunit/modules/Emails/EmailTest.php
  tests/unit/phpunit/modules/Favorites/FavoritesTest.php
  tests/unit/phpunit/modules/Leads/LeadTest.php
  tests/unit/phpunit/modules/OAuthKeys/OAuthKeyTest.php
  tests/unit/phpunit/modules/Opportunities/OpportunityTest.php
  tests/unit/phpunit/modules/SchedulersJobs/SchedulersJobTest.php
  tests/unit/phpunit/modules/Users/UserTest.php
  tests/unit/phpunit/modules/jjwg_Markers/jjwg_MarkersTest.php
Labels: Assessed

#6709 fix(Cron) - avoid printing js content in CLI commands
  modules/AOW_WorkFlow/aow_utils.php
Labels: Community Contribution

#8233 Backport various PHP 7.4 fixes
  data/Relationships/M2MRelationship.php
  data/Relationships/One2MRelationship.php
  include/ListView/ListViewDisplay.php
  include/SearchForm/SearchForm2.php
  modules/Emails/Email.php
  modules/Leads/Lead.php
  modules/jjwg_Areas/jjwg_Areas.php
  modules/jjwg_Maps/jjwg_Maps.php
Labels: Assessed

#8285 Fixed #6990 - Run Email Notification not working
  modules/Activities/EmailReminder.php
Labels: Assessed

#8053 Fixed #7874 - Unable to use custom _head.tpl file (alternative fix)
  include/Sugar_Smarty.php
  themes/SuiteP/tpls/header.tpl
Labels: Assessed, Community Contribution, Enhancement

#8160 Updated CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Assessed, Community Contribution

#8164 More inclusive language
  include/SubPanel/SubPanelTiles.php
  modules/Currencies/Currency.php
  modules/InboundEmail/InboundEmail.php
  modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
  modules/Users/language/en_us.lang.php
  modules/Users/views/view.list.php
Labels: Assessed, Community Contribution

#7879 Render phone fields as links
  include/Smarty/plugins/function.sugar_phone.php
  include/utils.php
  install/install_utils.php
  modules/Administration/Administration.php
  modules/Configurator/language/en_us.lang.php
  modules/Configurator/tpls/EditView.tpl
  tests/unit/phpunit/modules/Administration/AdministrationTest.php
  themes/SuiteP/include/DetailView/tab_panel_content.tpl
Labels: Assessed, Community Contribution, Enhancement

#8313 Add more TimeDate tests
  tests/unit/phpunit/include/TimeDateTest.php
Labels: Assessed

#8314 Fix parameter order for asserts in unit tests.
  tests/unit/phpunit/include/UtilsTest.php
  tests/unit/phpunit/include/utils/arrayUtilsTest.php
Labels: Assessed

#8100 FIX #8099 - Add a way to hide/show columnChooser in ListViews
  include/ListView/ListViewPagination.tpl
  themes/SuiteP/include/ListView/ListViewPagination.tpl
  themes/SuiteP/include/ListView/ListViewPaginationBottom.tpl
  themes/SuiteP/include/ListView/ListViewPaginationTop.tpl
Labels: Assessed, Community Contribution, Enhancement

#7798 Database character set configuration
  include/database/MysqlManager.php
  include/database/MysqliManager.php
  install.php
  install/installConfig.php
  install/install_utils.php
  install/language/en_us.lang.php
  install/suite_install/collations.php
  metadata/emails_beansMetaData.php
Labels: Assessed, Community Contribution, Enhancement, Needs Review

#8274 Provides fix for #8273
  include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Labels: Assessed

#8322 Remove Schedulers cron instructions from filter pop-up
  modules/Schedulers/views/view.list.php
Labels: Assessed
