Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-04, with the labels that each got.

#6742 Also set opt-in send/fail dates when sending emails through the action menu
  modules/Campaigns/WebToPersonCapture.php
  modules/EmailMan/EmailMan.php
Labels: Assessed, Community Contribution

#6732 Fixed #3598 - WebToPersonCapture: Fix assignment of multi select values
  modules/Campaigns/WebToPersonCapture.php
  tests/unit/phpunit/include/UtilsTest.php
Labels: Assessed, Community Contribution

#7139 Fix EmailManTest::testget_list_view_data
  tests/unit/phpunit/modules/Accounts/AccountTest.php
  tests/unit/phpunit/modules/EmailMan/EmailManTest.php
  tests/unit/phpunit/modules/Employees/EmployeeTest.php
  tests/unit/phpunit/modules/Leads/LeadTest.php
  tests/unit/phpunit/modules/Users/UserTest.php
Labels: Assessed

#7102 Don't delete the composer.lock when running tests on travis.
  .travis.yml
Labels: Assessed

#7113 phpunit: Various fixes for running with StateCheckerConfig::RUN_PER_TESTS
  modules/InboundEmail/InboundEmail.php
  tests/unit/phpunit/data/SugarBeanTest.php
  tests/unit/phpunit/include/MVC/Controller/SugarControllerTest.php
  tests/unit/phpunit/include/MVC/View/SugarViewTest.php
  tests/unit/phpunit/include/SugarEmailAddress/SugarEmailAddressTest.php
  tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
  tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php
  tests/unit/phpunit/modules/SchedulersJobs/SchedulersJobTest.php
Labels: Assessed, Community Contribution

#7088 Fixed #4297 - Error in Listview : Pagination - wrong "Selected" count
  jssource/src_files/include/javascript/sugar_3.js
Labels: Assessed, Community Contribution

#7089 Fixed #4297 - Error in Listview : Pagination - Bulk Action disabled a…
  jssource/src_files/include/javascript/sugar_3.js
Labels: Assessed, Community Contribution

#7151 Fix #6689 Task date_due not displaying in Activities subpanel
  modules/Tasks/metadata/subpanels/ForActivities.php
Labels: Assessed

#7126 Campaigns: escape subscribe()/unsubscribe() IDs and add tests
  modules/Campaigns/utils.php
  tests/unit/phpunit/modules/Campaigns/CampaignTest.php
Labels: Assessed, Community Contribution

#7130 Update composer.json
  composer.json
  composer.lock
Labels: Assessed

#7129 Update composer.json
  composer.json
  composer.lock
Labels: Assessed

#7100 Remove debug flags from codecept run commands in travis.yml
  .travis.yml
Labels: Community Contribution

#6762 Fixed 6761 - Api/V8 - Unable to Delete (unlink) relationships
  Api/V8/Config/routes.php
Labels: Assessed, Community Contribution

#6863 Fixed #6862 - API - Custom Routes file is stored separately from other custom files
  Api/Core/Loader/CustomLoader.php
Labels: Assessed, Community Contribution

#7182 Fixed #6761 - Api/V8 - Unable to Delete (unlink) relationships.
  Api/V8/Config/routes.php
Labels: Assessed

#7144 Fix API list total pages display
  Api/V8/JsonApi/Repository/Filter.php
  Api/V8/Param/Options/Filter.php
Labels: Assessed

#7161 Fixed #6452 - Api/V8 create record does not support unicode and space in attributes
  Api/V8/Param/Options/Attributes.php
Labels: Assessed

#7184 Fixed #6862 - Api/V8 - API - Custom Routes file is stored separately from other custom files
  Api/Core/Loader/CustomLoader.php
Labels: Assessed

#7143 Fix API relationship links
  Api/V8/JsonApi/Helper/RelationshipObjectHelper.php
Labels: Assessed

#7165 Links returned in the API should be relative to the base_uri
  Api/V8/JsonApi/Helper/PaginationObjectHelper.php
  Api/V8/JsonApi/Helper/RelationshipObjectHelper.php
Labels: API, Assessed, Community Contribution

#7208 FIX #7207 - Get Menu.php from custom/modules/MODULE_NAME
  include/MVC/View/SugarView.php
Labels: Assessed

#6976 FIX #6950 - Add wikimedia/composer-merge-plugin
  composer.json
Labels: Assessed, Community Contribution, Enhancement

#7142 Fix custom fields in sort/filter in the API
  Api/V8/JsonApi/Repository/Filter.php
  Api/V8/JsonApi/Repository/Sort.php
Labels: Assessed

#7147 Api - fix relate fields not populating on get_list
  Api/V8/BeanDecorator/BeanListRequest.php
Labels: Assessed

#7201 Fixed #6455 - The V8 API does not allow filtering by custom fields
  Api/V8/JsonApi/Repository/Filter.php
  Api/V8/JsonApi/Repository/Sort.php
Labels: Assessed

#5745 Fix #5746 - Unable to order results descending on get_relationships API method
  service/v4_1/SugarWebServiceUtilv4_1.php
Labels: Assessed, Community Contribution

#6744 Fix emails losing confirmed opt-in when converting a lead to a contact
  include/SugarEmailAddress/SugarEmailAddress.php
Labels: Assessed, Community Contribution, Needs Duplicated: Latest

#6680 Change default view on template to avoid date created/modified issues
  include/SugarObjects/templates/basic/metadata/detailviewdefs.php
  include/SugarObjects/templates/company/metadata/detailviewdefs.php
  include/SugarObjects/templates/file/metadata/detailviewdefs.php
  include/SugarObjects/templates/issue/metadata/detailviewdefs.php
  include/SugarObjects/templates/sale/metadata/detailviewdefs.php
Labels: Assessed, Needs Duplicated: LTS

#6048 Improve where clause when removing securitygroups relationships.
  data/Relationships/M2MRelationship.php
Labels: Community Contribution, Needs Duplicated: Latest

#7105 Fixed #5724 - Map Area - Import Option Fails : An Error has occurred
  modules/jjwg_Areas/Menu.php
Labels: Assessed, Community Contribution, Needs Duplicated: LTS

#7170 Fixed #7162 - Popup select All records btn hidden in SuiteCRM 7.11.x
  include/Popups/tpls/header.tpl
Labels: Needs Duplicated: LTS

#6745 Fixed #6037 - Reports: Fix adding relations from the first tree node
  modules/AOR_Reports/AOR_Report_Before.js
Labels: Assessed, Community Contribution, Needs Duplicated: LTS

#6128 #6126 fix(Workflow AnyChange condition) - decode prev value before compare
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Community Contribution, Needs Duplicated: LTS

#7199 Fixed #6864 - API - overzealous method visibility
  Api/V8/BeanDecorator/BeanListRequest.php
  Api/V8/BeanDecorator/BeanListResponse.php
  Api/V8/BeanDecorator/BeanManager.php
  Api/V8/Controller/ListViewController.php
  Api/V8/Controller/ListViewSearchController.php
  Api/V8/Controller/LogoutController.php
  Api/V8/Controller/ModuleController.php
  Api/V8/Controller/RelationshipController.php
  Api/V8/Controller/UserController.php
  Api/V8/Controller/UserPreferencesController.php
  Api/V8/JsonApi/Helper/AttributeObjectHelper.php
  Api/V8/JsonApi/Helper/RelationshipObjectHelper.php
  Api/V8/Service/ListViewSearchService.php
  Api/V8/Service/ListViewService.php
  Api/V8/Service/LogoutService.php
  Api/V8/Service/ModuleService.php
  Api/V8/Service/RelationshipService.php
  Api/V8/Service/UserPreferencesService.php
  Api/V8/Service/UserService.php
Labels: Assessed

#7214 Fixed DeleteRelationshipParams typo
  Api/V8/Config/routes.php
Labels: Assessed

#7213 Fixed relationship links url
  Api/V8/Service/RelationshipService.php
Labels: Assessed

#7226 Fixed #6480 - REST API - Prevent "Too few arguments to function Sugar…
  service/core/SugarWebServiceImpl.php
  service/v2_1/SugarWebServiceImplv2_1.php
  service/v3_1/SugarWebServiceImplv3_1.php
  service/v4/SugarWebServiceImplv4.php
  soap/SoapSugarUsers.php
Labels: Assessed

#7222 Fix bug_7220
  modules/AOS_Products_Quotes/line_items.js
Labels: Assessed

#7231 Fixed #7220 - Description/note fields in the contract line items formats the numeric values as currency
  modules/AOS_Products_Quotes/line_items.js
Labels: Assessed

#7229 Remove hardcoded encryption key
  Api/Core/Config/ApiConfig.php
  Api/V8/Config/services/middlewares.php
  composer.json
  composer.lock
  install/install_utils.php
  install/language/en_us.lang.php
  install/performSetup.php
  modules/Administration/QuickRepairAndRebuild.php
Labels: Assessed

#7230 Fixed #7221 - stdClass::$message_id undefinded for IMAP
  modules/InboundEmail/InboundEmail.php
Labels: Assessed

#7176 Remove codecov patch status
  codecov.yml
Labels: Assessed

#6843 Fixed #6540 - Hard coded text to language files
  lib/Search/UI/SearchThrowableHandler.php
  modules/Administration/Search/view.tpl
  modules/Administration/language/en_us.lang.php
  modules/Home/language/en_us.lang.php
Labels: Assessed

#7217 Fix AOS_Product_Categories test name.
  tests/acceptance/modules/AOS_Product_Categories/AOS_Product_CategoriesCest.php
Labels: Assessed, Community Contribution

#6834 Fixed #6829 - Cache composer packages on Travis CI
  .travis.yml
Labels: Assessed

#6499 Fix #6498 - handling of Account names and ids in Leads
  include/InlineEditing/InlineEditing.php
  include/generic/DeleteRelationship.php
  modules/Leads/LeadFormBase.php
  modules/Leads/tpls/DetailViewHeader.tpl
Labels: Assessed

#7227 Fixed #7188 - ACL doesn't work on JSON API V8
  Api/V8/Service/ModuleService.php
  lib/Exception/AccessDeniedException.php
Labels: Assessed
