Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-10, with the labels that each got.

#7950 Hotfix: Do not divide by adjustment if it equals 0
  include/ListView/ListViewSmarty.php
Labels: Assessed

#7929 Fixed #7928 - Upgrade wizard recommends composer update instead of composer install
  modules/UpgradeWizard/language/en_us.lang.php
Labels: Assessed

#7944 Fix #3129 Use correct Business Hours field name for opening hours check
  modules/Project/controller.php
Labels: Assessed

#7943 Fix #7942 add bool to eligible fields for merging
  modules/MergeRecords/Step3.php
Labels: Assessed

#7952 Update the .gitattributes export-ignore list
  .gitattributes
Labels: Assessed

#7924 FIX #7923 - Verify the variable is an array
  themes/SuiteP/include/SubPanel/tpls/SubPanelDynamic.tpl
Labels: Assessed, Community Contribution

#7913 FIX #7912 - Avoid PHP Notices in getVardefs() method
  include/generic/SugarWidgets/SugarWidgetField.php
Labels: Assessed, Community Contribution

#7904 Verify if $bean is_subclass_of SugarBean so we can check access
  include/Smarty/plugins/function.suite_check_access.php
Labels: Assessed, Community Contribution

#7951 Fixed #6691 - Typo in key - LBL_ORIGINAL_MESSAGE_SEPERATOR
  modules/Emails/EmailsController.php
  modules/Emails/language/en_us.lang.php
  modules/Emails/metadata/composeviewdefs.php
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/email.scss
Labels: Assessed

#3820 Fix search_by_module REST API
  service/v4/SugarWebServiceImplv4.php
Labels: Assessed, Community Contribution

#7900 Protect against illegal string offset warnings in aow_utils.
  modules/AOW_WorkFlow/aow_utils.php
Labels: Assessed, Community Contribution

#4471 Update DeleteRelationship.php
  include/generic/DeleteRelationship.php
Labels: Assessed

#6765 Fixed #321 Hitting enter in the password input saves the user but not the password
  modules/Users/views/view.edit.php
Labels: Assessed

#5464 Filter email templates on Events
  include/language/en_us.lang.php
  modules/FP_events/FP_events.php
  tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Labels: Assessed, Community Contribution

#7760 SugarEmail: Fix "to" field not being filled when the last record doesn't have an email
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
Labels: Community Contribution

#7515 Scheduled Reports: Fix report name relation and popup search
  modules/AOR_Scheduled_Reports/metadata/popupdefs.php
  modules/AOR_Scheduled_Reports/vardefs.php
  tests/unit/phpunit/modules/AOR_Scheduled_Reports/AOR_Scheduled_ReportsTest.php
Labels: Assessed, Community Contribution

#7641 Fixed #7396 - Update button clears DateTime parameter in Reports Module
  modules/AOR_Reports/AOR_Report.js
Labels: Community Contribution, Needs Updates

#6503 Add a SAML2 metadata endpoint
  include/MVC/Controller/entry_point_registry.php
  modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php
  modules/Users/authentication/SAML2Authenticate/SAML2Metadata.php
  tests/unit/phpunit/modules/Users/SAML2AuthenticateTest.php
Labels: Assessed, Community Contribution

#7892 FIXED #5652 - Ending spaces in language strings
  modules/Campaigns/language/en_us.lang.php
  modules/Cases/language/en_us.lang.php
  modules/Charts/language/en_us.lang.php
  modules/EmailMan/language/en_us.lang.php
  modules/Emails/language/en_us.lang.php
  modules/Roles/language/en_us.lang.php
  modules/Schedulers/language/en_us.lang.php
  modules/Users/language/en_us.lang.php
Labels: Assessed

#7978 FIX #7971 - Textarea in EditView overlaps other fields
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/editview.scss
Labels: Assessed, Enhancement

#7976 Replace deprecated array index accessors.
  include/utils.php
Labels: Community Contribution

#7986 Updated LoggerManager to use @method + code cleanup
  include/SugarLogger/LoggerManager.php
Labels: Assessed

#7994 Update config.yml to include 7.10.x branch
  .github/config.yml
Labels: Developer Tools

#7995 Fixed typos and made it grammatically better
  README.md
Labels: Assessed

#8018 Move RebuildConfig.php from using XTemplate to using Smarty.
  modules/Administration/RebuildConfig.php
  modules/Administration/templates/RebuildConfig.tpl
Labels: Assessed

#8020 Fixed a grammatical error in include/templates/Template.php
  include/templates/Template.php
Labels: Needs Review

#8000 Fix more PHP 7.4 array accessor deprecations
  include/Localization/Localization.php
  include/SugarFields/Fields/Relate/SugarFieldRelate.php
  include/TimeDate.php
  jssource/minify_utils.php
  modules/Calendar/CalendarDisplay.php
  modules/EmailMan/EmailMan.php
  modules/SugarFeed/SugarFeed.php
  modules/SugarFeed/linkHandlers/Link.php
  modules/UpgradeWizard/uw_utils.php
  modules/Users/User.php
Labels: Assessed

#8015 Make the pagination buttons on DetailView pages links.
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/detailview.scss
  themes/SuiteP/css/suitep-base/editview.scss
  themes/SuiteP/include/EditView/SugarVCR.tpl
Labels: Assessed

#7989 BeanFactory: Don't return deleted beans from the cache
  data/BeanFactory.php
  tests/unit/phpunit/data/SugarBeanTest.php
Labels: Assessed

#7990 AOW_WorkFlow: Delete all related beans when deleting a workflow
  modules/AOW_WorkFlow/AOW_WorkFlow.php
  tests/unit/phpunit/modules/AOW_WorkFlow/AOW_WorkFlowTest.php
Labels: Assessed

#8026 Fixed #8025 - OAuth Keys & OAuth2 Clients and Tokens icons are missing
  modules/Administration/metadata/adminpaneldefs.php
Labels: Assessed

#8030 Fixed #7738 - Email Template selection in email module is not working for 7.11.16 in Edge/IE11
  modules/Emails/include/ComposeView/EmailsComposeView.js
Labels: Assessed

#7587 Fixed #7586 - Unnecessary include in UserService
  Api/V8/Service/UserService.php
Labels: Assessed, Community Contribution

#7774 EmailMarketing: Add security groups support
  modules/EmailMarketing/vardefs.php
  tests/unit/phpunit/modules/SecurityGroups/SecurityGroupTest.php
Labels: Community Contribution, Enhancement

#7921 Complete previous fix when ElasticSearch disabled
  lib/Search/ElasticSearch/ElasticSearchHooks.php
Labels: Assessed

#8010 Skip cache building if custom class exists for dashlets
  include/Dashlets/DashletCacheBuilder.php
Labels: Assessed, Needs Documentation

#7981 Fixed paths to milestone image
  modules/AM_ProjectTemplates/gantt.php
  modules/Project/gantt.php
Labels: Community Contribution

#7771 Add dotenv support for the test environment
  .env.dist
  .gitignore
  composer.json
  composer.lock
  tests/_bootstrap.php
Labels: Assessed, Community Contribution

#8042 Ignore vendored library files in .codecov.yml
  .codecov.yml
Labels: Assessed

#8009 Update contributing.md
  .github/CONTRIBUTING.md
Labels: Assessed

#8058 Fix deprecated usages of implode
  include/OutboundEmail/OutboundEmail.php
  install/installConfig.php
  modules/AOR_Charts/AOR_Chart.php
  modules/ModuleBuilder/views/view.layoutview.php
Labels: Assessed

#8076 Fix a deprecated usage of join.
  include/SubPanel/SubPanelTiles.php
Labels: Community Contribution

#8039 Misc improvements to the acceptance tests.
  tests/_support/Step/Acceptance/Calls.php
  tests/_support/Step/Acceptance/InboundEmailTester.php
  tests/_support/Step/Acceptance/ModuleBuilder.php
  tests/_support/Step/Acceptance/Workflow.php
  tests/acceptance/Core/CompanyModuleCest.php
  tests/acceptance/modules/AOS_Products/AOS_ProductsCest.php
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/Campaigns/CampaignsCest.php
  tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Labels: Community Contribution

#8029 Updated mkdir calls to throw RuntimeExceptions
  include/UploadStream.php
  jssource/minify_utils.php
  lib/Robo/Plugin/Commands/TestEnvironmentCommands.php
  modules/Administration/UpgradeWizard_prepare.php
  modules/InboundEmail/InboundEmail.php
  modules/UpgradeWizard/upgradeMetaHelper.php
  modules/UpgradeWizard/uw_utils.php
Labels: Assessed

#8075 Fix misc PHP 7.4 deprecations
  modules/InboundEmail/InboundEmail.php
  modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
Labels: Assessed, Community Contribution

#8041 Remove BusinessCard-related code.
  modules/Contacts/BusinessCard.html
  modules/Contacts/BusinessCard.php
  modules/Contacts/ContactFormBase.php
  modules/Contacts/language/en_us.lang.php
  modules/Home/language/en_us.lang.php
  modules/Leads/language/en_us.lang.php
  modules/Prospects/language/en_us.lang.php
Labels: Community Contribution

#7844 SuiteP: Add html data tags to allow module and field identification
  themes/SuiteP/include/DetailView/tab_panel_content.tpl
  themes/SuiteP/include/EditView/tab_panel_content.tpl
  themes/SuiteP/tpls/header.tpl
Labels: Community Contribution, Enhancement

#8064 FIX #8063 - Change isset() to !empty()
  data/SugarBean.php
Labels: Assessed, Community Contribution

#7945 Fix for salesagility/SuiteCRM#7312
  include/GoogleSync/GoogleSyncBase.php
  include/GoogleSync/GoogleSyncHelper.php
  tests/unit/phpunit/include/GoogleSync/GoogleSyncTest.php
Labels: Assessed, Community Contribution

#8074 Remove deprecated helper files
  include/database/DBHelper.php
  include/database/DBManager.php
  include/database/FreeTDSHelper.php
  include/database/MssqlHelper.php
  include/database/MysqlHelper.php
  include/database/SqlsrvManager.php
  include/generic/LayoutManager.php
  modules/ModuleBuilder/parsers/relationships/AbstractRelationship.php
  modules/UpgradeWizard/uw_files.php
Labels: Assessed, Community Contribution

#7829 FIX #7828 - Robo tasks for common actions that are performed in Repair Administration module
  lib/Robo/Plugin/Commands/RepairCommands.php
Labels: Assessed, Community Contribution

#7834 Workflow: Properly delete records which are marked as deleted
  modules/AOW_Actions/actions/actionCreateRecord.php
Labels: Assessed, Community Contribution, Workflow

#8056 Fixed #7128 - Remove scheme to avoid mixed content error
  modules/jjwg_Maps/views/view.map_markers.php
Labels: Assessed, Community Contribution

#8073 Remove all uses of get_magic_quotes_gpc.
  include/utils.php
  install.php
  service/example/Rest_Proxy.php
Labels: Assessed, Community Contribution

#8060 Fix/apache log
  .travis.yml
  tests/travis_config_si.php
  travis.php.ini
Labels: Assessed

#7970 Fix #7969 - Cannot call logger
  lib/Search/SearchResults.php
Labels: Community Contribution

#7638 Fixed #7315 - Adding parameter date field in Reports module causes error in Browser console
  modules/AOR_Conditions/conditionLines.js
Labels: Assessed, Community Contribution

#8084 Remove dead code: Re:Remastered
  modules/Activities/SubPanelView.html
  modules/Activities/SubPanelView.php
  modules/Activities/SubPanelViewContacts.html
Labels: Assessed, Community Contribution

#7428 7427 fix(Audit) - show logs lines that was made by anonymous
  modules/Audit/Audit.php
Labels: Community Contribution

#7954 Fixed #7953 - Elasticsearch default size setting
  lib/Search/SearchQuery.php
Labels: Assessed, Community Contribution

#7901 Fixed #7886 - Elasticsearch Indexing memory usage
  lib/Search/ElasticSearch/ElasticSearchIndexer.php
  lib/Search/ElasticSearch/ElasticSearchModuleDataPuller.php
Labels: Community Contribution

#8085 Fix a deprecated string concatenation.
  modules/InboundEmail/InboundEmail.php
Labels: Community Contribution

#8086 Link contributors badge to contributors insights
  README.md
Labels: Assessed

#8088 Remove XML_HTMLSax3
  include/Pear/XML_HTMLSax3/HTMLSax3.php
  include/Pear/XML_HTMLSax3/HTMLSax3/Decorators.php
  include/Pear/XML_HTMLSax3/HTMLSax3/States.php
  include/Pear/XML_HTMLSax3/LICENSE
Labels: Assessed

#8067 Added the deprecated lowercase v8 API to codecov ignore list
  .codecov.yml
Labels: Assessed

#8068 Fixed #7764 - Undefined index: server_unique_key
  include/MVC/View/SugarView.php
Labels: Assessed

#8059 Added a check for SUGARCRM restrictions in htaccess
  install/install_utils.php
Labels: Assessed

#8108 Fix multiple date parameters in reports
  modules/AOR_Reports/aor_utils.php
Labels: Assessed

#7998 Fix #7997 - Datetime field caching issue
  include/SugarFields/Fields/Datetime/DetailView.tpl
Labels: Assessed

#7922 InboundEmail mime parser fix
  composer.json
  composer.lock
  include/Imap/ImapHandler.php
  modules/InboundEmail/InboundEmail.php
  tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php
Labels: Assessed, Needs Assessed

#8082 Fixed #1504 - check deleted flag on email_addresses and related bean
  include/SugarEmailAddress/SugarEmailAddress.php
  tests/unit/phpunit/include/SugarEmailAddress/SugarEmailAddressTest.php
Labels: Assessed, Community Contribution

#8119 Fixed ACLAction Travis failure
  include/TimeDate.php
  modules/ACLActions/ACLAction.php
  tests/api/V8/GetModulesMetaCest.php
Labels: Assessed

#8121 Remove references to old software
  install/suite_install/AdvancedOpenPortal.php
Labels: Assessed

#7856 #3736 fix(Import) - Pre-set import settings can't be deleted
  modules/Import/tpls/step2.tpl
  modules/Import/views/view.step2.php
Labels: Assessed, Community Contribution

#8065 FIXED #6314 - [language] Unused language strings (logout & login)
  include/language/en_us.lang.php
Labels: Assessed

#8013 Fix Activities and History Queries
  modules/Calls/metadata/subpanels/ForActivities.php
  modules/Calls/metadata/subpanels/ForHistory.php
  modules/Emails/metadata/subpanels/ForHistory.php
  modules/Emails/metadata/subpanels/ForUnlinkedEmailHistory.php
  modules/Emails/subpanels/ForHistory.php
  modules/Meetings/metadata/subpanels/ForActivities.php
  modules/Meetings/metadata/subpanels/ForHistory.php
  modules/Notes/metadata/subpanels/ForHistory.php
  modules/Tasks/metadata/subpanels/ForActivities.php
  modules/Tasks/metadata/subpanels/ForHistory.php
Labels: Assessed

#8128 Remove get_day_by_index_this_year from SugarDateTime.
  include/SugarDateTime.php
Labels: Community Contribution

#8127 Remove remove_redundant_http() from Account.
  modules/Accounts/Account.php
  tests/unit/phpunit/modules/Accounts/AccountTest.php
Labels: Community Contribution

#8125 Remove unused, deprecated functions from DBManager.php.
  include/database/DBManager.php
Labels: Community Contribution

#7753 Fix issue #6001
  modules/AM_TaskTemplates/vardefs.php
Labels: Assessed

#8124 Remove deprecated JSON functions encodeReal() and decodeReal()
  include/JSON.php
  modules/Home/QuickSearch.php
Labels: Community Contribution

#8129 Replace all uses of the deprecated db_utils functions.
  include/utils.php
  modules/ACLRoles/ACLRole.php
  modules/Campaigns/Charts.php
  modules/Charts/Dashlets/CampaignROIChartDashlet/CampaignROIChartDashlet.php
  modules/Charts/Dashlets/MyPipelineBySalesStageDashlet/MyPipelineBySalesStageDashlet.php
  modules/Charts/Dashlets/OutcomeByMonthDashlet/OutcomeByMonthDashlet.php
  modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
  modules/Charts/PredefinedChart.php
  modules/Charts/code/Chart_my_pipeline_by_sales_stage.php
  modules/Charts/code/Chart_outcome_by_month.php
  modules/Charts/code/Chart_pipeline_by_sales_stage.php
  modules/Contacts/Contact.php
  modules/Emails/Email.php
  modules/Schedulers/_AddJobsHere.php
  service/v4_1/SugarWebServiceImplv4_1.php
  soap/SoapData.php
  soap/SoapPortalUsers.php
  soap/SoapRelationshipHelper.php
Labels: Assessed, Community Contribution

#8123 Add parentheses to fix a deprecated string concatenation
  modules/AM_ProjectTemplates/project_table.php
Labels: Community Contribution

#8122 Remove deprecated encrypt_password function for User.
  modules/Users/User.php
  tests/unit/phpunit/modules/Users/UserTest.php
Labels: Assessed, Community Contribution

#8095 Remove SugarXHProf
  .codecov.yml
  .php_cs.dist
  codacy.yml
  codeception.dist.yml
  include/SugarXHprof/SugarXHprof.php
  include/SugarXHprof/xhprof_lib/display/typeahead_common.php
  include/SugarXHprof/xhprof_lib/display/xhprof.php
  include/SugarXHprof/xhprof_lib/utils/callgraph_utils.php
  include/SugarXHprof/xhprof_lib/utils/xhprof_lib.php
  include/SugarXHprof/xhprof_lib/utils/xhprof_runs.php
  include/entryPoint.php
Labels: Community Contribution

#8093 Remove all deprecated Smarty files.
  include/Smarty/Config_File.class.php
  include/Smarty/Smarty.class.php
  include/Smarty/Smarty_Compiler.class.php
  include/Smarty/internals/core.assemble_plugin_filepath.php
  include/Smarty/internals/core.assign_smarty_interface.php
  include/Smarty/internals/core.create_dir_structure.php
  include/Smarty/internals/core.display_debug_console.php
  include/Smarty/internals/core.get_include_path.php
  include/Smarty/internals/core.get_microtime.php
  include/Smarty/internals/core.get_php_resource.php
  include/Smarty/internals/core.is_secure.php
  include/Smarty/internals/core.is_trusted.php
  include/Smarty/internals/core.load_plugins.php
  include/Smarty/internals/core.load_resource_plugin.php
  include/Smarty/internals/core.process_cached_inserts.php
  include/Smarty/internals/core.process_compiled_include.php
  include/Smarty/internals/core.read_cache_file.php
  include/Smarty/internals/core.rm_auto.php
  include/Smarty/internals/core.rmdir.php
  include/Smarty/internals/core.run_insert_handler.php
  include/Smarty/internals/core.smarty_include_php.php
  include/Smarty/internals/core.write_cache_file.php
  include/Smarty/internals/core.write_compiled_include.php
  include/Smarty/internals/core.write_compiled_resource.php
  include/Smarty/internals/core.write_file.php
Labels: Community Contribution

#6981 The email address of the sender is hidden issue #6980
  modules/Emails/include/DetailView/EmailsDetailView.php
Labels: Assessed

#7737 Fix #7735: Added try catch on ListView when parsing subpanel query
  include/ListView/ListView.php
Labels: Assessed, Community Contribution

#7984 FIXED #7979 - Reports Total table squished
  modules/AOR_Reports/AOR_Report.php
  tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
Labels: Assessed

#8110 Fix #8109 - Reports Incorrect Module path
  modules/AOR_Reports/AOR_Report_Before.js
Labels: Assessed

#8151 Resolve issue with email templates
  include/language/en_us.lang.php
  modules/FP_events/FP_events.php
  modules/FP_events/vardefs.php
Labels: Assessed

#4045 Fix #4043 - Workflows with operator 'Equal To' on datetime fields not working properly
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Assessed, Community Contribution

#8142 Fix typos and improve grammar
  ModuleInstall/PackageManager/PackageController.php
  include/Dashlets/Dashlet.php
  include/ListView/ListView.php
  include/ListView/ListViewSubPanel.php
  include/MVC/View/views/view.metadata.php
  include/SugarEmailAddress/SugarEmailAddress.php
  include/javascript/tiny_mce/plugins/autosave/editor_plugin_src.js
  include/javascript/tiny_mce/plugins/paste/editor_plugin_src.js
  include/utils/sugar_file_utils.php
  modules/Administration/SyncInboundEmailAccounts.php
  modules/Campaigns/WizardEmailSetup.php
  modules/Emails/include/ListView/ListViewDataEmails.php
  modules/Import/views/view.step3.php
  modules/Schedulers/Scheduler.php
  service/core/SugarRestServiceImpl.php
  service/core/SugarWebServiceImpl.php
  service/core/webservice.php
  service/v2_1/SugarWebServiceImplv2_1.php
  service/v3/SugarWebServiceImplv3.php
  service/v3_1/SugarWebServiceImplv3_1.php
  service/v4/SugarWebServiceImplv4.php
  soap/SoapDeprecated.php
  soap/SoapHelperFunctions.php
  soap/SoapRelationshipHelper.php
  soap/SoapSugarUsers.php
  tests/api/v8/ModulesCest.php
Labels: Community Contribution

#8152 Update html-purifier to 4.12
  composer.json
  composer.lock
Labels: Assessed, Community Contribution
