Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-09, with the labels that each got.

#7711 Fixed #2928 Fixed #341 - clear Zend OPcache when writing files
  include/SugarCache/SugarCache.php
  include/utils/file_utils.php
  include/utils/sugar_file_utils.php
Labels: Assessed

#7643 Fixed #7622 - Make the code:coverage Robo command work outside of CI
  .travis.yml
  lib/Robo/Plugin/Commands/CodeCoverageCommands.php
Labels: Assessed

#7198 Feature/robo api
  lib/Robo/Plugin/Commands/ApiCommands.php
  lib/Robo/Traits/CliRunnerTrait.php
Labels: Assessed

#7659 Fix icons not rendering properly in Alerts.
  modules/Alerts/templates/default.tpl
Labels: Community Contribution

#7822 FIX #7821 - User name is not aligned in 1200px to 1600px screens
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/navbar.scss
Labels: Assessed

#7833 SugarFeed: Various fixes for 7.10.19/20 regressions
  modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
  modules/SugarFeed/SugarFeed.php
Labels: Assessed

#7816 Removing an item from subpanel should only require the item edit access right
  include/ListView/ListViewSubPanel.php
Labels: Assessed

#7809 Robo: Add a --filter option to tests:unit for filtering tests
  lib/Robo/Plugin/Commands/TestRunCommands.php
Labels: Assessed

#7837 FIX #7836 - Robo task to compile css in a custom theme
  lib/Robo/Plugin/Commands/BuildCommands.php
Labels: Assessed

#7746 FIX #7675 - Add a function to compare properly indices definitios
  include/database/DBManager.php
  include/database/MysqlManager.php
  include/utils/array_utils.php
  tests/unit/phpunit/include/utils/arrayUtilsTest.php
Labels: Assessed

#7839 Fixed #7838 - 'Undefined index: docType' PHP notice
  download.php
  include/SugarFields/Fields/File/SugarFieldFile.php
Labels: Assessed

#7797 Fixed #7779 - PHP Fatal error in modules/Connectors
  modules/Connectors/connectors/sources/ext/rest/twitter/config.php
Labels: Assessed

#7826 FIX #7825 - Now we translate the title tag for recently viewed links
  themes/SuiteP/tpls/_headerModuleList.tpl
Labels: Assessed

#7857 Temporarily revert PHP 5.5 from the Travis build
  .travis.yml
Labels: Assessed

#7655 Fixed #7648 - Case Module: Description field not showing after Save and continue
  modules/Cases/views/view.edit.php
Labels: Community Contribution

#7813 FIX #7810 - Pencil present in Top Menu for users with non editing permission
  include/Smarty/plugins/function.suite_check_access.php
  themes/SuiteP/tpls/_headerModuleList.tpl
Labels: Assessed

#5537 Fix #5520 Do not clear existing attachments when loading a template
  modules/Emails/Email.php
  modules/Emails/EmailsController.php
  modules/Emails/include/ComposeView/ComposeView.tpl
  modules/Emails/include/ComposeView/EmailsComposeView.js
  modules/Emails/views/view.compose.php
Labels: Assessed

#7650 Fix 'customMetadate' typo in DashletGeneric.php.
  include/Dashlets/DashletGeneric.php
Labels: Community Contribution

#7606 Remove HTMLPurifier ConfigForm.js file.
  jssource/src_files/include/HTMLPurifier/standalone/HTMLPurifier/Printer/ConfigForm.js
Labels: Assessed, Community Contribution

#7529 Codacy
  .codacy.yml
  .pullapprove.yml
  phpcs.xml
Labels: Assessed

#7193 Unused Import
  Api/V8/Param/GetRelationshipParams.php
  include/LangException.php
  lib/API/JsonApi/v1/Filters/Parsers/FilterParser.php
  lib/API/JsonApi/v1/Filters/Validators/OperatorValidator.php
  lib/API/JsonApi/v1/JsonApi.php
  lib/API/JsonApi/v1/Links.php
  lib/API/JsonApi/v1/Repositories/FilterRepository.php
  lib/API/JsonApi/v1/Resource/Relationship.php
  lib/API/JsonApi/v1/Resource/Resource.php
  lib/API/OAuth2/Repositories/AccessTokenRepository.php
  lib/API/OAuth2/Repositories/ClientRepository.php
  lib/API/v8/Controller/ApiController.php
  lib/API/v8/Exception/ApiException.php
  lib/API/v8/Exception/BadRequestException.php
  lib/API/v8/Exception/ConflictException.php
  lib/API/v8/Exception/EmptyBodyException.php
  lib/API/v8/Exception/ForbiddenException.php
  lib/API/v8/Exception/IdAlreadyExistsException.php
  lib/API/v8/Exception/InvalidJsonApiRequestException.php
  lib/API/v8/Exception/InvalidJsonApiResponseException.php
  lib/API/v8/Exception/ModuleNotFoundException.php
  lib/API/v8/Exception/NotAcceptableException.php
  lib/API/v8/Exception/NotAllowedException.php
  lib/API/v8/Exception/NotFoundException.php
  lib/API/v8/Exception/NotImplementedException.php
  lib/API/v8/Exception/ReservedKeywordNotAllowedException.php
  lib/API/v8/Exception/UnsupportedMediaTypeException.php
  lib/API/v8/Library/ModulesLib.php
  lib/API/v8/container/RelationshipRepository.php
  lib/Exception/Exception.php
  lib/Exception/InvalidArgumentException.php
  lib/Robo/Plugin/Commands/CodeCoverageCommands.php
  tests/SuiteCRM/Test/Driver/PhpBrowserDriver.php
  tests/SuiteCRM/Test/SuitePHPUnit_Framework_TestCase.php
  tests/_support/Helper/Acceptance.php
  tests/_support/Helper/WebDriverHelper.php
  tests/_support/InstallTester.php
  tests/_support/ModuleFields.php
  tests/_support/Page/AccountsModule.php
  tests/_support/Page/BasicModule.php
  tests/_support/Page/CompanyModule.php
  tests/_support/Page/Design.php
  tests/_support/Page/FileModule.php
  tests/_support/Page/IssueModule.php
  tests/_support/Page/PersonModule.php
  tests/_support/Page/SaleModule.php
  tests/_support/Step/Acceptance/ModuleBuilder.php
  tests/acceptance/Core/SaleModuleCest.php
  tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
  tests/api/V8/DeleteModuleCest.php
  tests/unit/phpunit/Api/Core/Loader/CustomLoaderTest.php
  tests/unit/phpunit/SuitePHPUnit_Framework_TestCase.php
  tests/unit/phpunit/data/SugarBeanTest.php
  tests/unit/phpunit/include/UtilsTest.php
  tests/unit/phpunit/include/utils/fileUtilsTest.php
  tests/unit/phpunit/service/v4/SugarWebServiceUtilv4Test.php
Labels: Assessed

#7819 #7817 fix(WorkFlow) - added option to filter WorkFlows by module name
  modules/AOW_WorkFlow/metadata/searchdefs.php
Labels: Assessed, Enhancement

#7783 FIX #7780 - Bad css format in Date and Date Range Inputs in search forms
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/listview.scss
Labels: Assessed

#7847 Fix emails being sent from 'Root User'.
  modules/Emails/Email.php
Labels: Assessed

#7871 FIX #7870 - Improvements in css for date_input and labels in EditView
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/editview.scss
Labels: Assessed

#7867 AOR_Report Group Headers: Fixing #7393 and #7644, replacing #7645
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7864 FIXED #7642 - Title/Job Title [translations] (|Title - Job Title)
  modules/Contacts/language/en_us.lang.php
  modules/Employees/language/en_us.lang.php
  modules/Leads/language/en_us.lang.php
  modules/Prospects/language/en_us.lang.php
  modules/Users/language/en_us.lang.php
Labels: Assessed

#7815 Save email addresses before saving company/person
  include/SugarObjects/templates/company/Company.php
  include/SugarObjects/templates/person/Person.php
Labels: Assessed

#7814 Fix a sql query bug for quote purchase subpanel
  modules/AOS_Products/AOS_Products.php
Labels: Assessed

#7627 Update sugar_3.js to fix a MassUpdate undefined error.
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
Labels: Assessed, Community Contribution

#7877 FIX #7875 - Wrong render in DateRangeInput using "Between" Option
  include/SugarFields/Fields/Datetimecombo/RangeSearchForm.tpl
Labels: Assessed

#7818 InboundEmailTest: Make tests independent to make them work with the state checker
  tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php
Labels: Assessed

#7858 Fix Issue when importing non UTF-8 CSV file
  modules/Import/Importer.php
  modules/Import/views/view.step3.php
Labels: Assessed

#7898 Fixed #7552 - AOR Reports - Mysqli_query failed when execute Report as normal User
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7899 Fix 'Undefined index: leads_id' notices in AOR_Report.php
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7925 Enable Delete button in Actions menu
  modules/Users/views/view.detail.php
Labels: Assessed, Community Contribution

#7918 Fix issue with french translation
  modules/Emails/EmailUI.php
Labels: Assessed, Community Contribution

#7906 Gitattributes + codeception.dist.yml
  .gitattributes
  .gitignore
  .travis.yml
  codacy.yml
  codeception.dist.yml
  codeception.yml
  include/fonts/License.html
  include/javascript/mozaik/colorpicker/css/colorpicker.css
  include/javascript/mozaik/colorpicker/css/layout.css
  include/javascript/mozaik/colorpicker/index.html
  include/javascript/mozaik/colorpicker/js/colorpicker.js
  include/javascript/mozaik/colorpicker/js/eye.js
  include/javascript/mozaik/colorpicker/js/jquery.js
  include/javascript/mozaik/colorpicker/js/layout.js
  include/javascript/mozaik/colorpicker/js/utils.js
  include/javascript/tiny_mce/plugins/spellchecker/editor_plugin.js
  include/javascript/yui/build/history/assets/blank.html
  include/ytree/TreeView/css/check/tree.css
  modules/AOR_Charts/lib/pChart/imagemap.js
Labels: Assessed

#7907 Update composer.lock + codecov.yml + rebuild SASS/JS
  .codecov.yml
  composer.lock
  include/SugarCharts/Jit/js/mySugarCharts.js
  include/javascript/sugar_3.js
Labels: Assessed
