Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-05, with the labels that each got.

#6883 fixed bug that removes Email_Address_Removed_In_Email_Body if email i…
  include/HtmlSanitizer.php
Labels: Assessed, Requires Review

#7164 Fixed issue with undecoded subjects coming from Emails DetailView
  modules/Emails/Compose.php
Labels: Community Contribution

#6387 Bug fix create language cache in multilanguage system
  include/SugarObjects/LanguageManager.php
Labels: Assessed, Community Contribution

#7173 Fix V8 API authorization header passing with apache+php-fpm
  Api/Core/app.php
  install/install_utils.php
  modules/Administration/UpgradeAccess.php
Labels: Assessed, Community Contribution

#4198 fixing a recursion issue on reminders
  modules/Calendar/CalendarUtils.php
  modules/Calendar/controller.php
  modules/Calls/Call.php
  modules/Meetings/Meeting.php
  modules/Reminders/Reminder.php
  modules/Reminders/controller.php
Labels: Assessed

#7263 Travis due date fix
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/History/HistoryCest.php
Labels: Assessed

#7274 Fixed install syntax error
  install.php
Labels: Assessed

#6505 Fixed #6504 - Fix and implement proper bounce email handling
  modules/Campaigns/ProcessBouncedEmails.php
  modules/Emails/Email.php
  modules/InboundEmail/InboundEmail.php
  modules/Notes/Note.php
  tests/unit/phpunit/modules/Emails/EmailTest.php
Labels: Assessed, Community Contribution

#7269 FIX #7268 - Fatal Error with PHP 7.3
  include/SugarLogger/LoggerManager.php
Labels: Community Contribution

#7124 travis-ci: Switch the PHP 7.x jobs to Ubuntu 16.04
  .travis.yml
Labels: Assessed, Community Contribution

#7292 FIX #7291 - Field name in ProspectLists is now varchar(255)
  modules/ProspectLists/vardefs.php
Labels: Assessed

#7246 Add return to function
  include/SubPanel/SubPanelDefinitions.php
Labels: Assessed, Community Contribution

#7289 FIX #7288 - Field name in Campaigns is now varchar(255)
  modules/Campaigns/vardefs.php
Labels: Assessed

#7248 Fixed #7183 - My Cases dashlet searchFields status default values are incorrect
  modules/Cases/Dashlets/MyCasesDashlet/MyCasesDashlet.data.php
Labels: Assessed

#7134 Fixed - #7133 - Fix Changes in Studio do not make an override file
  modules/DynamicFields/DynamicField.php
Labels: Assessed

#7251 FIX #7250 - Remove PHP Notices in include/ListView/ListViewSmarty.php
  include/ListView/ListViewSmarty.php
Labels: Assessed, Community Contribution

#7283 Fixed #6915 - File OAuth2Tokens/metadata/editviewdefs.php is Missing.
  themes/SuiteP/include/ListView/ListViewGeneric.tpl
Labels: Assessed

#6987 *WIP Fixed #6869 - Saving user resets preferences
  modules/Users/User.php
  modules/Users/controller.php
  tests/_support/Step/Acceptance/Administration.php
  tests/_support/Step/Acceptance/UsersTester.php
  tests/acceptance/modules/Users/UsersCest.php
Labels: Assessed

#7286 FIXED #5652 - Ending spaces in language strings
  modules/Campaigns/language/en_us.lang.php
  modules/Home/language/en_us.lang.php
Labels: Assessed

#6852 Manage delegate mssql
  modules/FP_events/controller.php
Labels: Assessed, Community Contribution, Needs Duplicated: Latest, Needs Updates

#7297 Fix support forum link
  install/dbConfig_a.php
  install/installConfig.php
  install/installDisabled.php
  install/installType.php
  install/license.php
  install/old_php.php
  install/performSetup.php
  install/ready.php
  install/siteConfig_a.php
  install/welcome.php
Labels: Assessed

#7302 Fixed #6420 - Campaigns: don't send test emails to lists no longer linked to the campaign
  modules/EmailMan/EmailManDelivery.php
Labels: Assessed

#7262 Replace $db global variable in a bunch of files
  modules/Charts/Dashlets/OpportunitiesByLeadSourceDashlet/OpportunitiesByLeadSourceDashlet.php
  modules/Emails/EmailUI.php
  modules/Leads/views/view.convertlead.php
  modules/Project/Project.php
  modules/Project/chart.php
  modules/Project/controller.php
Labels: Assessed, Community Contribution

#7300 Fixed #6445 - Campaign Wizard: Assign current user when creating a new template
  modules/EmailTemplates/EmailTemplateData.php
  tests/bootstrap.php
  tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Labels: Assessed

#7240 EmailTemplates: Improve image url replacement
  include/StateSaver.php
  modules/EmailTemplates/EmailTemplate.php
  modules/EmailTemplates/Save.php
  tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Labels: Assessed, Community Contribution
