Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-06, with the labels that each got.

#7258 Update codeception
  composer.json
  composer.lock
Labels: Assessed

#7270 Fixed #6140 - Switch from league/url to league/uri due to deprecation
  composer.json
  composer.lock
  lib/API/v8/Library/ModulesLib.php
Labels: Assessed

#7341 Fix zero padding issue with openssl decryption
  service/core/SoapHelperWebService.php
Labels: Assessed

#7339 Fixed #2049 - 7.7.2 - Calendar Activities are off by 1 day
  jssource/src_files/modules/Calendar/Cal.js
  modules/Calendar/Cal.js
Labels: Assessed

#7329 StateChecker: Don't save hash debug traces
  .travis.yml
Labels: Assessed

#7346 Remove Functional test suite files.
  tests/_support/FunctionalTester.php
  tests/_support/Helper/Functional.php
  tests/functional.suite.yml
  tests/functional/_bootstrap.php
Labels: Assessed

#7311 fixes #7308 - Sub-Theme changes don't always update
  .gitignore
  lib/Robo/Plugin/Commands/BuildCommands.php
Labels: Assessed

#7343 Fix #5173 by disabling linebreak replacement on email fields during inline edit
  include/InlineEditing/inlineEditing.js
Labels: Assessed

#7253 Fixed issue with undecoded subjects coming from Emails DetailView
  modules/Emails/Compose.php
Labels: Assessed

#7287 Remove PclZip
  .php_cs.dist
  ModuleInstall/PackageManager/PackageManager.php
  codeception.yml
  codecov.yml
  composer.json
  composer.lock
  files.md5
  include/pclzip/gnu-lgpl.txt
  include/pclzip/pclzip.lib.php
  include/pclzip/readme.txt
  include/utils/php_zip_utils.php
  include/utils/zip_utils.php
  install/download_modules.php
  install/install_utils.php
  modules/Administration/DiagnosticRun.php
  modules/Administration/UpgradeWizardCommon.php
  modules/Administration/views/view.backups.php
  modules/ModuleBuilder/MB/MBPackage.php
  modules/UpgradeWizard/index.php
  modules/UpgradeWizard/preflightJson.php
  modules/UpgradeWizard/silentUpgrade_dce_step1.php
  modules/UpgradeWizard/silentUpgrade_dce_step2.php
  modules/UpgradeWizard/silentUpgrade_step1.php
  modules/UpgradeWizard/silentUpgrade_step2.php
  modules/UpgradeWizard/upgradeTimeCounter.php
  tests/unit/phpunit/include/utils/zipUtilsTest.php
Labels: Assessed

#7355 Run PHPUnit outside the tests directory
  .travis.yml
  lib/Robo/Plugin/Commands/CodeCoverageCommands.php
  tests/bootstrap.php
  tests/unit/phpunit/lib/SuiteCRM/Robo/Commands/CodeCoverageCommandsTest.php
Labels: Assessed, Community Contribution

#7352 Remove demo test suite.
  tests/_support/DemoTester.php
  tests/_support/Helper/Demo.php
  tests/demo.suite.yml
  tests/demo/DemoCest.php
  tests/demo/_bootstrap.php
Labels: Assessed, Community Contribution

#7235 FIX #7234 - Get subpaneldefs.php from custom/modules/MODULE_NAME/metadata
  include/SubPanel/SubPanelDefinitions.php
Labels: Community Contribution

#7404 Add RoboFile.php to root directory again.
  RoboFile.php
Labels: Assessed

#7403 Remove unused Codeception unit test suite files.
  tests/_support/Helper/Unit.php
  tests/_support/UnitTester.php
  tests/unit.suite.yml
Labels: Community Contribution

#7398 Fix #6343 handling posix not allowed on some Linux systems
  cron.php
  include/utils.php
  modules/UpgradeWizard/systemCheck.php
  modules/UpgradeWizard/uw_ajax.php
  modules/UpgradeWizard/uw_utils.php
Labels: Assessed

#7275 API - Enable getting deleted records in Get List
  Api/V8/Param/GetModulesParams.php
  Api/V8/Service/ModuleService.php
Labels: Assessed

#7353 FIX #7351 - last_name and first_name are too short
  modules/Users/vardefs.php
Labels: Assessed, Community Contribution

#7356 Configurable elasticsearch host in acceptance test
  tests/_support/Helper/WebDriverHelper.php
  tests/acceptance/lib/Search/ElasticsearchCest.php
Labels: Assessed, Community Contribution

#7408 Info about making PR's in GitHub project README
  README.md
Labels: Assessed

#7395 Fixed #7238 - Incorrect user_id saved in users_signatures table when admin updates a signature
  modules/Users/SaveSignature.php
Labels: Assessed, Community Contribution

#7206 Add php-cs-fixer to composer.json as a dev dependency.
  .php_cs.dist
  composer.json
  lib/Robo/Plugin/Commands/CodingStandardCommands.php
Labels: Assessed, Community Contribution

#7410 StateChecker: disable save_traces by default
  .travis.yml
  include/StateCheckerConfig.php
  include/StateCheckerTrait.php
Labels: Community Contribution

#7412 Fixed #7107 - MysqliManager: always remove STRICT_TRANS_TABLES from sql_mode
  .travis.yml
  include/database/MysqliManager.php
Labels: Community Contribution, Databases

#7257 Favorite link in active Module does not get generated
  themes/SuiteR/tpls/_headerModuleList.tpl
Labels: Community Contribution

#7420 Fixed #7391 - DB Error on audit logging large multi select fields.
  include/database/DBManager.php
  modules/Audit/Audit.php
Labels: Assessed

#7414 Remove explicit timeouts in acceptance tests.
  tests/_support/Step/Acceptance/Calls.php
  tests/_support/Step/Acceptance/Dashboard.php
  tests/_support/Step/Acceptance/DetailView.php
  tests/_support/Step/Acceptance/EditView.php
  tests/_support/Step/Acceptance/ListView.php
  tests/_support/Step/Acceptance/Meetings.php
  tests/_support/Step/Acceptance/ModuleBuilder.php
  tests/_support/Step/Acceptance/NavigationBar.php
  tests/_support/Step/Acceptance/Workflow.php
  tests/acceptance/Core/ModuleBuilderFieldsCest.php
  tests/acceptance/modules/Accounts/AccountsCest.php
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/History/HistoryCest.php
Labels: Assessed, Requires Review

#7394 Fixed #7393 - Displaying dropdown db value instead of dropdown label in group header in Reports module
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed, Community Contribution, Reports, Requires Review

#7418 Remove repetitive instance URL visits from tests
  tests/_support/AcceptanceTester.php
  tests/acceptance/Core/BasicModuleCest.php
  tests/acceptance/Core/CompanyModuleCest.php
  tests/acceptance/Core/FileModuleCest.php
  tests/acceptance/Core/IssueModuleCest.php
  tests/acceptance/Core/ModuleBuilderFieldsCest.php
  tests/acceptance/Core/PersonModuleCest.php
  tests/acceptance/Core/SaleModuleCest.php
  tests/acceptance/LoginCest.php
  tests/acceptance/modules/AM_Project_Templates/AM_Project_TemplatesCest.php
  tests/acceptance/modules/AOK_KnowledgeBase/AOK_KnowledgeBaseCest.php
  tests/acceptance/modules/AOK_Knowledge_Base_Categories/AOK_Knowledge_Base_CategoriesCest.php
  tests/acceptance/modules/AOR_Reports/AOR_ReportsCest.php
  tests/acceptance/modules/AOS_PDF_Templates/AOS_PDF_TemplatesCest.php
  tests/acceptance/modules/AOS_Product_Categories/AOS_Product_CategoriesCest.php
  tests/acceptance/modules/AOS_Products/AOS_ProductsCest.php
  tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
  tests/acceptance/modules/Accounts/AccountsCest.php
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/Calendar/CalendarCest.php
  tests/acceptance/modules/Calls/CallsCest.php
  tests/acceptance/modules/Campaigns/CampaignsCest.php
  tests/acceptance/modules/Cases/CasesCest.php
  tests/acceptance/modules/Contacts/ContactsCest.php
  tests/acceptance/modules/Contracts/ContractsCest.php
  tests/acceptance/modules/Documents/DocumentsCest.php
  tests/acceptance/modules/EmailMan/EmailManCest.php
  tests/acceptance/modules/EmailTemplates/EmailTemplatesCest.php
  tests/acceptance/modules/Emails/EmailsCest.php
  tests/acceptance/modules/FP_Event_Locations/FP_Event_LocationsCest.php
  tests/acceptance/modules/FP_Events/FP_EventsCest.php
  tests/acceptance/modules/History/HistoryCest.php
  tests/acceptance/modules/Home/HomeCest.php
  tests/acceptance/modules/Invoices/InvoicesCest.php
  tests/acceptance/modules/Leads/LeadsCest.php
  tests/acceptance/modules/Meetings/MeetingsCest.php
  tests/acceptance/modules/Notes/NotesCest.php
  tests/acceptance/modules/Opportunities/OpportunitiesCest.php
  tests/acceptance/modules/Projects/ProjectsCest.php
  tests/acceptance/modules/Quotes/QuotesCest.php
  tests/acceptance/modules/Spots/SpotsCest.php
  tests/acceptance/modules/Surveys/SurveysCest.php
  tests/acceptance/modules/TargetLists/TargetListsCest.php
  tests/acceptance/modules/Targets/TargetsCest.php
  tests/acceptance/modules/Tasks/TasksCest.php
  tests/acceptance/modules/Users/UsersCest.php
  tests/acceptance/modules/jjwg_Address_Cache/jjwg_Address_CacheCest.php
  tests/acceptance/modules/jjwg_Areas/jjwg_AreasCest.php
  tests/acceptance/modules/jjwg_Maps/jjwg_MapsCest.php
  tests/acceptance/modules/jjwg_Markers/jjwg_MarkersCest.php
  tests/install/UserWizardCest.php
Labels: Assessed, Community Contribution

#7436 Simplify the acceptance and install suite configs.
  tests/acceptance.suite.yml
  tests/install.suite.yml
Labels: Assessed

#4319 Fixed #715 - Custom Required Field not flagging
  jssource/src_files/include/javascript/sugar_3.js
Labels: Assessed

#7372 Fix issue #7370
  modules/AOR_Reports/aor_utils.php
  modules/AOW_WorkFlow/aow_utils.php
Labels: Assessed

#7367 FIXED #7319 - Activity Stream dashlet "reply" function doesn't appear to do anything
  modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
Labels: Assessed

#7399 Fixed #3727 - IMAP server delete button on DetailView
  modules/Emails/EmailsController.php
  modules/Emails/include/ListView/DeleteEmailAction.js
  modules/Emails/include/ListView/ListViewHeader.js
  modules/Emails/language/en_us.lang.php
  modules/Emails/metadata/detailviewdefs.php
  modules/Emails/metadata/listviewdefs.php
  modules/Emails/metadata/nonimporteddetailviewdefs.php
Labels: Assessed

#7444 IMAP StateSaver test fix
  include/Imap/ImapHandlerFactory.php
  tests/unit/phpunit/include/Imap/ImapHandlerFactoryTest.php
Labels: Requires Review

#7453 Cache Composer files in Travis. (hotfix-7.10.x PR)
  .travis.yml
Labels: Assessed

#7451 Add composer validate job in Travis.
  .travis.yml
Labels: Assessed

#7449 Remove some incomplete tests and miscellaneous formatting fixes for the unit test suite
  tests/unit/phpunit/data/SugarBeanTest.php
  tests/unit/phpunit/include/MVC/SugarApplicationTest.php
  tests/unit/phpunit/include/MVC/View/views/view.ajaxuiTest.php
  tests/unit/phpunit/include/MVC/View/views/view.classicTest.php
  tests/unit/phpunit/include/MVC/View/views/view.detailTest.php
  tests/unit/phpunit/include/MVC/View/views/view.editTest.php
  tests/unit/phpunit/include/MVC/View/views/view.importvcardsaveTest.php
  tests/unit/phpunit/include/MVC/View/views/view.sugarpdfTest.php
  tests/unit/phpunit/lib/SuiteCRM/Exception/ExceptionTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/CurrentLanguageTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/ModuleLanguageTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/PathsTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/StringValidatorTest.php
  tests/unit/phpunit/lib/SuiteCRM/Utility/SuiteLoggerTest.php
  tests/unit/phpunit/modules/ACLActions/ACLActionTest.php
  tests/unit/phpunit/modules/ACLRoles/ACLRoleTest.php
  tests/unit/phpunit/modules/AOD_Index/AOD_IndexTest.php
  tests/unit/phpunit/modules/AOP_Case_Updates/AOP_Case_UpdatesTest.php
  tests/unit/phpunit/modules/AOR_Charts/AOR_ChartTest.php
  tests/unit/phpunit/modules/AOR_Conditions/AOR_ConditionTest.php
  tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
  tests/unit/phpunit/modules/AOR_Scheduled_Reports/AOR_Scheduled_ReportsTest.php
  tests/unit/phpunit/modules/AOS_Contracts/AOS_ContractsTest.php
  tests/unit/phpunit/modules/AOS_Invoices/AOS_InvoicesTest.php
  tests/unit/phpunit/modules/AOS_Line_Item_Groups/AOS_Line_Item_GroupsTest.php
  tests/unit/phpunit/modules/AOS_PDF_Templates/AOS_PDF_TemplatesTest.php
  tests/unit/phpunit/modules/AOS_Products/AOS_ProductsTest.php
  tests/unit/phpunit/modules/Accounts/AccountTest.php
  tests/unit/phpunit/modules/Alerts/AlertTest.php
Labels: Assessed

#7442 Replace most instances of $I->wait(n) with waitForX.
  tests/_support/Step/Acceptance/Calls.php
  tests/_support/Step/Acceptance/Campaigns.php
  tests/_support/Step/Acceptance/ListView.php
  tests/_support/Step/Acceptance/ModuleBuilder.php
  tests/_support/Step/Acceptance/NavigationBar.php
  tests/acceptance/Core/ModuleBuilderFieldsCest.php
  tests/acceptance/Core/PersonModuleCest.php
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/History/HistoryCest.php
  tests/acceptance/modules/Home/HomeCest.php
  tests/acceptance/modules/Meetings/MeetingsCest.php
  tests/acceptance/modules/Users/UsersCest.php
  tests/acceptance/modules/jjwg_Maps/jjwg_MapsCest.php
Labels: Assessed

#7437 Remove wait from Codeception Travis env
  .travis.yml
  tests/_envs/travis-ci-hub.yml
  tests/_support/Step/Acceptance/Calls.php
  tests/_support/Step/Acceptance/DetailView.php
  tests/_support/Step/Acceptance/ModuleBuilder.php
  tests/acceptance/Core/ModuleBuilderFieldsCest.php
  tests/acceptance/modules/Accounts/AccountsCest.php
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/History/HistoryCest.php
Labels: Assessed

#7439 Update password hash to use php password_hash by default
  modules/Users/User.php
Labels: Assessed

#4335 Fixed #1840 - Meetings in scheduler shifted by one hour
  jssource/src_files/include/javascript/jsclass_async.js
Labels: Assessed, Needs Duplicated: Latest

#7413 Fixed #7402 - Popup selects are broken
  include/javascript/popup_helper.js
  jssource/src_files/include/javascript/popup_helper.js
Labels: Assessed

#7460 Fixed #7156 - Slow SQL query in include/SugarFolders/SugarFolders.php…
  include/SugarFolders/SugarFolders.php
Labels: Assessed

#7450 Update composer.lock to include php-cs-fixer.
  composer.json
  composer.lock
Labels: Assessed

#7461 Fixed #7249 - Admin user cannot edit another user's Mail Accounts
  modules/Emails/EmailUIAjax.php
Labels: Assessed

#7462 Update password hash to use php password_hash by default
  modules/Users/User.php
Labels: Assessed

#7456 Fix #7455 Leads conversion - handle copying photo file, if present
  modules/Leads/views/view.convertlead.php
Labels: Assessed

#7481 7.8.x md5
  files.md5
Labels: Assessed
