Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-01, with the labels that each got.

#6674 Fixed #4872 - Fix some async subpanel actions failing if refresh_page=1
  include/SubPanel/SubPanelTiles.js
  include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php
  jssource/src_files/include/SubPanel/SubPanelTiles.js
Labels: Assessed, Community Contribution

#6653 campaing wizard: fix template editor being shown in all steps
  modules/Campaigns/WizardMarketing.html
Labels: Assessed, Community Contribution

#6704 Fixed #5508 - Upgrade phpMailer to 6.x
  codeception.yml
  composer.json
  composer.lock
  files.md5
  include/SugarPHPMailer.php
  include/phpmailer/LICENSE
  include/phpmailer/VERSION
  include/phpmailer/class.phpmailer.php
  include/phpmailer/class.smtp.php
  include/phpmailer/extras/htmlfilter.php
  include/phpmailer/language/phpmailer.lang-ar.php
  include/phpmailer/language/phpmailer.lang-br.php
  include/phpmailer/language/phpmailer.lang-ca.php
  include/phpmailer/language/phpmailer.lang-ch.php
  include/phpmailer/language/phpmailer.lang-cz.php
  include/phpmailer/language/phpmailer.lang-de.php
  include/phpmailer/language/phpmailer.lang-dk.php
  include/phpmailer/language/phpmailer.lang-es.php
  include/phpmailer/language/phpmailer.lang-et.php
  include/phpmailer/language/phpmailer.lang-fi.php
  include/phpmailer/language/phpmailer.lang-fo.php
  include/phpmailer/language/phpmailer.lang-fr.php
  include/phpmailer/language/phpmailer.lang-hu.php
  include/phpmailer/language/phpmailer.lang-it.php
  include/phpmailer/language/phpmailer.lang-ja.php
  include/phpmailer/language/phpmailer.lang-nl.php
  include/phpmailer/language/phpmailer.lang-no.php
  include/phpmailer/language/phpmailer.lang-pl.php
  include/phpmailer/language/phpmailer.lang-ro.php
  include/phpmailer/language/phpmailer.lang-ru.php
  include/phpmailer/language/phpmailer.lang-se.php
  include/phpmailer/language/phpmailer.lang-tr.php
  include/phpmailer/language/phpmailer.lang-zh.php
  include/phpmailer/language/phpmailer.lang-zh_cn.php
  tests/unit/phpunit/modules/Emails/EmailTest.php
Labels: Assessed

#6486 Fixed #6485 - Users: Display opt-in ticks also for external email clients
  modules/Emails/EmailUI.php
  modules/Users/User.php
Labels: Assessed, Community Contribution

#6713 Fix email related to
  modules/Emails/views/view.import.php
Labels: Assessed

#6738 Fixed #6717 - Create Role - Delete column does not display properly
  modules/ACLRoles/EditAllBody.tpl
Labels: Assessed

#6734 Add email account name to inbox button
  modules/Emails/include/ListView/ListViewHeader.js
Labels: Assessed

#6757 Fixed #6484 - Fix image insertion with mozaik
  modules/Emails/javascript/Email.js
Labels: Community Contribution

#6725 unit tests: force enable E_ALL in bootstrap
  tests/bootstrap.php
Labels: Assessed, Community Contribution

#6769 Fixed #6758 - [language]Duplicated language strings - develop branch
  include/language/en_us.lang.php
Labels: Assessed

#6775 Fixed #6484 for LTS - Fix image insertion with mozaik
  modules/Emails/javascript/Email.js
Labels: Community Contribution

#6782 Email view not working after upgrade from v.7.10.11 to 7.10.12 + 7.11
  modules/Emails/include/ListView/ListViewDataEmails.php
Labels: Community Contribution

#6813 Fixed #6810 - Campaign page failure/imapfactory
  modules/Campaigns/WizardEmailSetup.php
Labels: Assessed

#6804 Fixed #532 - Add the edit/remove button to Project Tasks subpanel
  modules/ProjectTask/metadata/subpanels/default.php
Labels: Assessed

#6814 Fixed #6810 - Campaign page failure/imapfactory
  modules/Campaigns/WizardEmailSetup.php
Labels: Assessed

#6803 Fixed #532 - Add the edit/remove button to Project Tasks subpanel
  modules/ProjectTask/metadata/subpanels/default.php
Labels: Assessed

#6770 Don't delete the composer.lock when running tests on travis.
  .travis.yml
Labels: Community Contribution

#6805 Fixed #6786 - Edit item list replace spaces with html entity "%20"
  modules/ModuleBuilder/javascript/SimpleList.js
Labels: Assessed

#6807 Fixed #6786 - Edit item list replace spaces with html entity "%20"(h…
  modules/ModuleBuilder/javascript/SimpleList.js
Labels: Assessed

#6715 Fix #4361 Use Parameter $imageJSONEncode if returning sprites, too
  include/SugarTheme/SugarTheme.php
Labels: Community Contribution

#6774 EmailTemplates: Use html2text library for generating the text only body
  composer.json
  composer.lock
  modules/EmailTemplates/EmailTemplate.php
  tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Labels: Community Contribution, Enhancement, Needs Duplicated: LTS, Needs Duplicated: Latest
