Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-07, with the labels that each got.

#7488 Fixed #7421 - Use of ampersand (&) in email subject sends email subject misformatted
  modules/Emails/Email.php
Labels: Community Contribution

#7477 Remove unused webDriverHelper variables
  tests/acceptance/Core/BasicModuleCest.php
  tests/acceptance/Core/CompanyModuleCest.php
  tests/acceptance/Core/FileModuleCest.php
  tests/acceptance/Core/IssueModuleCest.php
  tests/acceptance/Core/ModuleBuilderFieldsCest.php
  tests/acceptance/Core/PersonModuleCest.php
  tests/acceptance/Core/SaleModuleCest.php
  tests/acceptance/LoginCest.php
  tests/acceptance/modules/AM_Project_Templates/AM_Project_TemplatesCest.php
  tests/acceptance/modules/AOK_KnowledgeBase/AOK_KnowledgeBaseCest.php
  tests/acceptance/modules/AOK_Knowledge_Base_Categories/AOK_Knowledge_Base_CategoriesCest.php
  tests/acceptance/modules/AOR_Reports/AOR_ReportsCest.php
  tests/acceptance/modules/AOS_PDF_Templates/AOS_PDF_TemplatesCest.php
  tests/acceptance/modules/AOS_Product_Categories/AOS_Product_CategoriesCest.php
  tests/acceptance/modules/AOS_Products/AOS_ProductsCest.php
  tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
  tests/acceptance/modules/Accounts/AccountsCest.php
  tests/acceptance/modules/Activities/ActivitiesCest.php
  tests/acceptance/modules/Calendar/CalendarCest.php
  tests/acceptance/modules/Calls/CallsCest.php
  tests/acceptance/modules/Campaigns/CampaignsCest.php
  tests/acceptance/modules/Cases/CasesCest.php
  tests/acceptance/modules/Contacts/ContactsCest.php
  tests/acceptance/modules/Contracts/ContractsCest.php
  tests/acceptance/modules/Documents/DocumentsCest.php
  tests/acceptance/modules/EmailMan/EmailManCest.php
  tests/acceptance/modules/EmailTemplates/EmailTemplatesCest.php
  tests/acceptance/modules/Emails/EmailsCest.php
  tests/acceptance/modules/FP_Event_Locations/FP_Event_LocationsCest.php
  tests/acceptance/modules/FP_Events/FP_EventsCest.php
  tests/acceptance/modules/History/HistoryCest.php
  tests/acceptance/modules/Home/HomeCest.php
  tests/acceptance/modules/Invoices/InvoicesCest.php
  tests/acceptance/modules/Leads/LeadsCest.php
  tests/acceptance/modules/Meetings/MeetingsCest.php
  tests/acceptance/modules/Notes/NotesCest.php
  tests/acceptance/modules/Opportunities/OpportunitiesCest.php
  tests/acceptance/modules/Projects/ProjectsCest.php
  tests/acceptance/modules/Quotes/QuotesCest.php
  tests/acceptance/modules/Spots/SpotsCest.php
  tests/acceptance/modules/Surveys/SurveysCest.php
  tests/acceptance/modules/TargetLists/TargetListsCest.php
  tests/acceptance/modules/Targets/TargetsCest.php
  tests/acceptance/modules/Tasks/TasksCest.php
  tests/acceptance/modules/Users/UsersCest.php
  tests/acceptance/modules/jjwg_Address_Cache/jjwg_Address_CacheCest.php
  tests/acceptance/modules/jjwg_Areas/jjwg_AreasCest.php
  tests/acceptance/modules/jjwg_Maps/jjwg_MapsCest.php
  tests/acceptance/modules/jjwg_Markers/jjwg_MarkersCest.php
Labels: Assessed, Community Contribution

#7345 Get ChromeDriver's latest release in Robo task.
  lib/Robo/Plugin/Commands/TestEnvironmentCommands.php
Labels: Assessed, Community Contribution

#7433 Clean up codeception environments
  .gitignore
  tests/README.md
  tests/_envs/chrome-driver.yml
  tests/_envs/custom.dist.yml
  tests/_envs/selenium-chrome.yml
  tests/_envs/selenium-fhd.yml
  tests/_envs/selenium-firefox.yml
  tests/_envs/selenium-hd.yml
  tests/_envs/selenium-hub.yml
  tests/_envs/selenium-ipad-2.yml
  tests/_envs/selenium-iphone-6.yml
  tests/_envs/selenium-xga.yml
Labels: Assessed, Community Contribution

#7518 Fixed #7407 - "Users may send as themselves" broken - Invalid address: (punyEncode)
  modules/Emails/EmailsDataAddressCollector.php
Labels: Assessed

#7517 Fixed #7267 - Database Failure after upgrading to Version 7.11.4
  modules/Meetings/metadata/subpanels/ForHistory.php
Labels: Assessed

#7422 Fixed #7390 - Unable to set Minimum Password Length in Password Management
  modules/Administration/PasswordManager.php
Labels: Assessed, Community Contribution, Needs Updates

#7476 Fixed #6992 - Group Email Inbox accounts doesn't respect reply as option in admin
  modules/Emails/EmailUI.php
Labels: Assessed

#3909 Partially fixed #3756 - Calendar pop-ups now auto close after 500ms w…
  jssource/src_files/modules/Calendar/Cal.js
  modules/Calendar/Cal.js
Labels: Assessed, Community Contribution

#7475 Fixed #5552 - Inbound Email Auto-reply send email without Attachments
  modules/InboundEmail/InboundEmail.php
Labels: Assessed

#6374 Fixed #6046 - SQL "rank" is a reserved word, can't be used as a field…
  metadata/user_feedsMetaData.php
Labels: Assessed

#6305 *WIP Fixed #2620 - Need to import multiple contacts from single VCARD .vcf file
  include/vCard.php
Labels: Assessed

#7487 Fixed #7409 - Managing Delegates Removes main windows Scrolling
  include/javascript/checkbox.js
Labels: Assessed, Community Contribution

#7535 Misc automated testing improvements.
  lib/Robo/Plugin/Commands/TestEnvironmentCommands.php
  tests/_envs/custom.dist.yml
Labels: Assessed

#7503 Scheduled Reports: Enable security groups support and add the subpanel
  modules/AOR_Scheduled_Reports/metadata/subpaneldefs.php
  modules/AOR_Scheduled_Reports/vardefs.php
  tests/unit/phpunit/modules/SecurityGroups/SecurityGroupTest.php
Labels: Assessed, Enhancement

#7523 Fixed #6935 - Cookie path is not respected if globally set
  include/MVC/SugarApplication.php
Labels: Assessed

#7510 FIX #7509 - Using prefix index to not hit Key threshold in MySQL5.6/UTF-8
  modules/Users/vardefs.php
Labels: Assessed

#7524 Fixed #6470 - Email module: Inline image not shown in received/sent email
  modules/InboundEmail/InboundEmail.php
Labels: Assessed

#7514 Fixed #7511 - Silent installer tries to do unknown things on completion
  install.php
Labels: Assessed

#7218 Fix #5754 - Error with custom fields on getQuery from One2Many relationships (7.10.x)
  data/Relationships/One2MBeanRelationship.php
Labels: Assessed, Community Contribution

#7545 Revert "FIXED #3756 - Popup Studio and Calendar don't auto-close"
  modules/ModuleBuilder/javascript/ModuleBuilder.js
Labels: Assessed

#7565 Add wait to HomeCest so it won't flake.
  tests/acceptance/modules/Home/HomeCest.php
Labels: Assessed

#7374 Robo test-running commands
  lib/Robo/Plugin/Commands/TestRunCommands.php
Labels: Assessed, Community Contribution

#7561 Add a get_current_language() helper function
  data/SugarBean.php
  include/MVC/SugarApplication.php
  include/utils.php
  modules/Activities/EmailReminder.php
  modules/Emails/EmailUI.php
  modules/Home/QuickSearch.php
  modules/Home/sitemap.php
  modules/Users/authentication/EmailAuthenticate/EmailAuthenticateUser.php
  service/JsonRPCServer/JsonRPCServer.php
  service/JsonRPCServer/JsonRPCServerCalls.php
  tests/unit/phpunit/include/UtilsTest.php
  vCard.php
Labels: Assessed

#7573 Remove sugar references
  include/EditView/SubpanelQuickEdit.php
  include/MVC/View/views/view.quickcreate.php
  include/MVC/View/views/view.quickedit.php
  modules/Connectors/tpls/administration.tpl
  modules/Contacts/views/view.quickcreate.php
  modules/Home/SubpanelEdits.php
  modules/ModuleBuilder/tpls/Preview/layoutView.tpl
  modules/ModuleBuilder/tpls/Preview/listView.tpl
  modules/ModuleBuilder/tpls/layoutView.tpl
  modules/ModuleBuilder/tpls/listView.tpl
  modules/Project/views/view.quickedit.php
  modules/Users/views/view.quickedit.php
  themes/SuiteP/modules/ModuleBuilder/tpls/layoutView.tpl
Labels: Assessed

#7569 Fixed #4881 - Detail view of no imported email is different as imported + missing time unit + attachments
  modules/Emails/metadata/detailviewdefs.php
  modules/Emails/metadata/nonimporteddetailviewdefs.php
Labels: Assessed

#7563 Fixed #7547 - use correct login image on install.php
  install.php
Labels: Assessed

#7568 FIX issue #7567: Missing Contracts from selection of Related to: field
  include/language/en_us.lang.php
Labels: Assessed, Enhancement

#7582 Fix codecov path
  .travis.yml
Labels: Assessed

#7492 Replace the createAccount method
  tests/_support/Step/Acceptance/Accounts.php
  tests/acceptance/_bootstrap.php
  tests/acceptance/modules/Accounts/AccountsCest.php
  tests/acceptance/modules/Users/UsersCest.php
Labels: Assessed

#7584 FIXED #7209 - Inline Edit alert Even if I dont make a change.
  include/InlineEditing/inlineEditing.js
Labels: Assessed

#7588 Fix pagination button class
  themes/SuiteP/css/Dawn/style.css
  themes/SuiteP/css/Day/style.css
  themes/SuiteP/css/Dusk/style.css
  themes/SuiteP/css/Night/style.css
  themes/SuiteP/css/suitep-base/listview.scss
  themes/SuiteP/include/ListView/ListViewPaginationTop.tpl
Labels: Assessed

#7542 ListView: Fix selection when switch from "select all" to "select page"
  include/ListView/ListViewDisplay.php
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
Labels: Assessed

#7541 ListView: Fix the selection count when executing an action without any selection
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
Labels: Assessed

#7538 Fixed #7304 - ListView: Fix selection count for the "Select All" case
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
  modules/SecurityGroups/AssignGroups.php
  themes/SuiteP/include/ListView/ListViewSelectObjects.tpl
Labels: Assessed

#7583 Backport hotfix robo tasks
  lib/Robo/Plugin/Commands/BuildCommands.php
  lib/Robo/Plugin/Commands/CleanCacheCommands.php
  lib/Robo/Plugin/Commands/UpgradeCommands.php
  lib/Robo/Traits/CliRunnerTrait.php
Labels: Assessed

#7612 Fixed #7608 - A non-numeric value encountered at ListViewSubPanel.php
  include/ListView/ListView.php
Labels: Assessed

#7611 Fixed #7599 - Unwanted email generated in case creation & update
  modules/AOP_Case_Updates/CaseUpdatesHook.php
Labels: Assessed

#7571 Fixed #2464 - Logo upload function is not working
  modules/Configurator/UploadFileCheck.php
  modules/Configurator/language/en_us.lang.php
Labels: Assessed

#7530 Fix missing function getAssignedEmailsCountForUsers
  modules/Emails/EmailUI.php
Labels: Assessed

#7603 Remove include/timezone/, it hasn't been used for many years.
  codeception.yml
  include/timezone/timezones.php
Labels: Assessed

#7536 Cleanup files created by acceptance tests between test runs
  tests/_support/Helper/Acceptance.php
Labels: Assessed

#7601 Fixed #7298 - Emails 'Bulk Action' is disabled after upgrade to 7.10.16
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
  modules/InboundEmail/InboundEmail.php
Labels: Assessed

#7624 Fixed email settings "data error"
  modules/Emails/EmailUI.php
Labels: Assessed

#7154 Fixes SugarPHPMailer encountered an error: Could not access file
  include/SugarPHPMailer.php
Labels: Assessed, Community Contribution

#7474 SecuritySuite 3.1.16
  include/EditView/EditView2.php
  include/EditView/SecurityGroups.tpl
  include/formbase.php
  modules/Leads/views/view.convertlead.php
  modules/SecurityGroups/AssignGroups.php
  modules/SecurityGroups/SaveConfig.php
  modules/SecurityGroups/SaveSecurityGroupUserRelationship.php
  modules/SecurityGroups/SecurityGroup.php
  modules/SecurityGroups/config.php
  modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
  modules/SugarFeed/SugarFeed.php
  soap/SoapSugarUsers.php
Labels: Assessed, Community Contribution

#6850 SAML2: Use php-saml from composer
  modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/CHANGELOG
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/LICENSE
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/README.md
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/_toolkit_loader.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/advanced_settings_example.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/certs/README
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/compatibility.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/endpoints/acs.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/endpoints/metadata.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/endpoints/sls.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/extlib/xmlseclibs/CHANGELOG.txt
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/extlib/xmlseclibs/LICENSE
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/extlib/xmlseclibs/xmlseclibs.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml/AuthRequest.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml/Metadata.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml/Response.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml/Settings.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml/XmlSec.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Auth.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/AuthnRequest.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Constants.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Error.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/IdPMetadataParser.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/LogoutRequest.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/LogoutResponse.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Metadata.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Response.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Settings.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/Utils.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/saml-schema-assertion-2.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/saml-schema-authn-context-2.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/saml-schema-authn-context-types-2.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/saml-schema-metadata-2.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/saml-schema-protocol-2.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/sstc-metadata-attr.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/sstc-saml-attribute-ext.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/sstc-saml-metadata-algsupport-v1.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/sstc-saml-metadata-ui-v1.0.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/xenc-schema.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/xml.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/schemas/xmldsig-core-schema.xsd
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/lib/Saml2/version.json
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/locale/en_US/LC_MESSAGES/phptoolkit.mo
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/locale/en_US/LC_MESSAGES/phptoolkit.po
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/locale/es_ES/LC_MESSAGES/phptoolkit.mo
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/locale/es_ES/LC_MESSAGES/phptoolkit.po
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/php-saml/settings_example.php
  modules/Users/authentication/SAML2Authenticate/lib/onelogin/saml.php
Labels: Assessed, Community Contribution
