Repository SuiteCRM/SuiteCRM, pull requests merged in 2019-03, with the labels that each got.

#6815 unittests: Fixes for PHP 7.3
  ModuleInstall/ModuleScanner.php
  data/SugarBean.php
  include/utils/file_utils.php
  modules/AOW_WorkFlow/aow_utils.php
Labels: Assessed, Community Contribution

#5985 Fix unified search "no results" page
  modules/Home/UnifiedSearch.php
Labels: Assessed, Community Contribution

#7010 Fix link to testing documentation. [ci-skip]
  tests/README.md
Labels: Assessed, Community Contribution

#7019 Fixed #2531 - 7.10.4 - Report Writer - Boolean Field will not export to CSV
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7018 Fixed #2531 - 7.10.4 - Report Writer - Boolean Field will not export to CSV
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7016 Fixed #6978 - Hosting company is blocking ports because of YamlRunnerTest.php
  composer.json
Labels: Assessed

#4606 Add ability to have Notes on a Campaign
  include/language/en_us.lang.php
  modules/Campaigns/Campaign.php
  modules/Campaigns/language/en_us.lang.php
  modules/Campaigns/metadata/subpaneldefs.php
  modules/Campaigns/vardefs.php
  modules/Campaigns/views/view.detail.php
  modules/Notes/vardefs.php
  tests/unit/phpunit/modules/Campaigns/CampaignTest.php
Labels: Assessed, Community Contribution, Enhancement

#7049 Give cookie a default value to stop from throwing notices
  themes/SuiteP/tpls/_headerModuleList.tpl
  themes/SuiteP/tpls/header.tpl
Labels: Assessed, Community Contribution

#7040 FIX #7032 - Add setLevelMapping method
  include/SugarLogger/LoggerManager.php
Labels: Assessed, Community Contribution

#7039 FIX #7032 - Add setLevelMapping method
  include/SugarLogger/LoggerManager.php
Labels: Assessed, Community Contribution

#7041 fix: Any Phone search on Contacts module added missing field phone_home on SearchFields
  modules/Contacts/metadata/SearchFields.php
Labels: Assessed, Community Contribution

#7043 Fix random unittest error in SugarControllerTest
  tests/unit/phpunit/include/MVC/Controller/SugarControllerTest.php
Labels: Assessed, Community Contribution

#7046 Fixed #5662 - EmailTemplate: Fix images URLs not being converted with mozaik
  modules/EmailTemplates/EmailTemplate.php
  tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Labels: Assessed, Community Contribution

#7026 Fixed #6185 - Top menu mouse out does not close sub
  themes/SuiteP/tpls/_headerModuleList.tpl
Labels: Assessed

#7023 Fixed #6185 - Top menu mouse out does not close sub
  themes/SuiteP/tpls/_headerModuleList.tpl
Labels: Assessed

#6941 Fixed issue with tab panel and quick create form
  themes/SuiteP/include/DetailView/DetailView.tpl
Labels: Assessed

#6802 Allow for clean cache command to use config'd cache_dir (plus clean up)
  lib/Robo/Plugin/Commands/CleanCacheCommands.php
Labels: Assessed, Community Contribution

#6907 Reduce travis output - DotReporter
  .travis.yml
  suitecrm_version.php
Labels: Assessed

#7058 Fixed #7054 - Email body blank when sent as plaintext only
  modules/InboundEmail/InboundEmail.php
Labels: Assessed

#7012 Codecov threshold
  codecov.yml
Labels: Assessed

#7013 Codecov threshold
  codecov.yml
Labels: Assessed

#6896 Fixed #675 - Suitecrm 7.3.2 Calendar entries are not displayed
  modules/Calendar/CalendarActivity.php
Labels: Assessed

#6639 bugfix 3592
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7061 FIX #7051 - Fixing a limit of 2.147.483 seconds for autoRefresh
  include/Dashlets/Dashlet.php
Labels: Assessed, Community Contribution

#7062 FIX #7051 - Fixing a limit of 2.147.483 seconds for autoRefresh
  include/Dashlets/Dashlet.php
Labels: Assessed, Community Contribution

#7036 Increase minimum recommended memory to 64Mb (for 7.8.x)
  install/ready.php
Labels: Assessed

#7035 Increase minimum recommended memory to 64Mb (for 7.10.x)
  install/ready.php
Labels: Assessed

#7082 EmailTemplates: Fix undefined property error when creating a new template
  modules/EmailTemplates/EditView.php
Labels: Assessed, Community Contribution

#6860 Reports: Hide inaccessible modules in the reports editor
  modules/AOR_Reports/AOR_Report.php
  modules/AOW_WorkFlow/aow_utils.php
Labels: Assessed, Community Contribution

#6942 Fixed issue with tab panel and quick create form
  themes/SuiteP/include/DetailView/DetailView.tpl
Labels: Assessed

#6937 Fixed #5918 - Activity Stream elapsed time calculation
  modules/SugarFeed/SugarFeed.php
  tests/tests/modules/SugarFeed/SugarFeedTest.php
Labels: Assessed

#6912 Fixed #551 - add functionality to save new labels for relationships
  modules/ModuleBuilder/parsers/parser.label.php
Labels: Assessed

#7064 Use the provided method to make sure the index exists
  include/SugarObjects/templates/basic/Basic.php
Labels: Assessed, Community Contribution

#7072 Fixed #7067 - InLine Date Edit bug - Call to a member function format() on boolean
  include/InlineEditing/InlineEditing.php
Labels: Assessed

#7073 Fixed #7067 - InLine Date Edit bug - Call to a member function format() on boolean
  include/InlineEditing/InlineEditing.php
Labels: Assessed

#7060 Fix warnings in log
  include/ListView/ListViewSmarty.php
  modules/Emails/include/ListView/ListViewDataEmails.php
Labels: Assessed

#7045 EmailTemplates: Only show subpanels in the DetailView
  modules/EmailTemplates/views/view.classic.php
Labels: Assessed, Community Contribution

#7031 Fixed #7025 - Sent date for emails in History View Summary is incorrect
  modules/Activities/Popup_picker.php
Labels: Assessed

#6986 Issue: #6985 Fix Exception on Repair/Quick Repair and Rebuild
  lib/Search/ElasticSearch/ElasticSearchIndexer.php
Labels: Assessed, Community Contribution

#6806 WYSIWYG Field type core contribution
  include/Smarty/plugins/modifier.htmlparser.php
  include/SugarFields/Fields/Text/SugarFieldText.php
  include/SugarFields/Fields/Wysiwyg/DetailView.tpl
  include/SugarFields/Fields/Wysiwyg/EditView.tpl
  include/SugarFields/Fields/Wysiwyg/ListView.tpl
  include/SugarFields/Fields/Wysiwyg/SugarFieldWysiwyg.php
  include/SugarFields/Fields/Wysiwyg/css/wysiwyg-editview.css
  include/generic/SugarWidgets/SugarWidgetFieldwysiwyg.php
  modules/AOS_PDF_Templates/templateParser.php
  modules/DynamicFields/templates/Fields/Forms/wysiwyg.php
  modules/DynamicFields/templates/Fields/Forms/wysiwyg.tpl
  modules/DynamicFields/templates/Fields/TemplateWysiwyg.php
  modules/ModuleBuilder/language/en_us.lang.php
  themes/SuiteP/tpls/_head.tpl
Labels: Community Contribution

#7085 FIX Error in SearchForm2.php when having a function in field definition
  include/SearchForm/SearchForm2.php
Labels: Assessed, Community Contribution

#6823 UI change: Displaying proper popup of list of PDF Templates.
  include/javascript/checkbox.js
  modules/AOS_PDF_Templates/formLetter.php
Labels: Assessed, Community Contribution

#6946 Fix priorities when loading language files
  include/SugarObjects/LanguageManager.php
Labels: Assessed, Community Contribution, Requires Review

#6007 AOR reports: Export to pdf with page numbers
  modules/AOR_Reports/controller.php
Labels: Community Contribution

#6948 Fixed #6729 - Email Style Issue - Black screen
  modules/Emails/include/ComposeView/EmailsComposeView.js
Labels: Assessed

#7074 Fixed #3592 - AOR Report - Date parameter doesn't work with any value of type 'Period'
  modules/AOR_Reports/AOR_Report.php
Labels: Assessed

#7034 Fixed - Removed sugar reference
  include/utils.php
  install.php
  install/download_modules.php
  modules/UpgradeWizard/silentUpgrade_dce_step1.php
  modules/UpgradeWizard/silentUpgrade_dce_step2.php
  modules/UpgradeWizard/silentUpgrade_step1.php
  modules/UpgradeWizard/silentUpgrade_step2.php
Labels: Assessed, Requires Review

#6733 AOR Reports: Add a security groups subpanel
  modules/AOR_Reports/metadata/subpaneldefs.php
Labels: Community Contribution, Enhancement

#5969 Fixed #5968 - AOR Reports - incorrect start date calculated for LastQuarter period when in the 4th quarter
  modules/AOR_Reports/aor_utils.php
Labels: Assessed

#5973 Fixed #5967 - AOR Reports - incorrect calculation for date quarter periods
  modules/AOR_Reports/aor_utils.php
Labels: Assessed

#7044 Fix Content-Type header missing in some cases for the getImage entry point
  include/SugarTheme/SugarTheme.php
  include/SugarTheme/getImage.php
  tests/unit/phpunit/include/SugarTheme/SugarThemeTest.php
Labels: Assessed, Community Contribution, Needs Updates

#7099 Fix/mssql folder support
  include/SugarFolders/SugarFolders.php
Labels: Assessed

#5972 Fix #5971 - Send email with Workflow using Meetings module breaks parent_id
  modules/Emails/vardefs.php
Labels: Assessed, Community Contribution

#6792 Performing an upgrade from the CLI #6710
  lib/Robo/Plugin/Commands/UpgradeCommands.php
Labels: Assessed

#7091 Fix obscured milestone radio buttons in Project Templates
  modules/AM_ProjectTemplates/css/style.css
Labels: Assessed

#7106 phpunit: Reduce test noise & make output test methods work
  include/StateCheckerPHPUnitTestCaseAbstract.php
  tests/unit/phpunit/include/MVC/Controller/SugarControllerTest.php
  tests/unit/phpunit/include/MVC/View/views/view.vcardTest.php
Labels: Assessed, Community Contribution

#7101 Fix (little) v8 API for v7.10.10+
  lib/API/OAuth2/Repositories/AccessTokenRepository.php
  lib/API/OAuth2/Repositories/ClientRepository.php
  lib/API/public/index.php
Labels: Community Contribution

#7120 Fix: For MS SQL Support
  include/SugarFolders/SugarFolders.php
Labels: Assessed

#7127 Add href mailto for email links even when using internal email client
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
  modules/Emails/EmailUI.php
Labels: Assessed, Community Contribution
