Repository SuiteCRM/SuiteCRM, pull requests merged in 2022-02, with the labels that each got.

#9496 Fix #9496 - Cannot save dropdown values
  modules/Studio/DropDowns/DropDownHelper.php
Labels: Status:Assessed, Branch:Hotfix

#9391 Fixed #7842 Do not reset email addresses list upon saving #9390
  include/SugarEmailAddress/SugarEmailAddress.php
Labels: Status:Assessed, Status: Ready to Merge

#9479 Fixed #2857 - No dynamic refreshing in dashboard
  themes/SuiteP/include/Dashlets/DashletHeader.tpl
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge

#9481 fix#9480 slow to get imap mailboxex with a million records in emails …
  modules/Emails/vardefs.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge

#9507 Add getters to SearchResultsController
  lib/Search/UI/SearchResultsController.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge

#9525 Fix #9468 - Adding Security Suite subpanels to new custom modules
  include/SugarObjects/templates/basic/metadata/metafiles.php
  include/SugarObjects/templates/basic/metadata/subpaneldefs.php
  include/SugarObjects/templates/company/metadata/metafiles.php
  include/SugarObjects/templates/company/metadata/subpaneldefs.php
  include/SugarObjects/templates/file/metadata/metafiles.php
  include/SugarObjects/templates/file/metadata/subpaneldefs.php
  include/SugarObjects/templates/issue/metadata/metafiles.php
  include/SugarObjects/templates/issue/metadata/subpaneldefs.php
  include/SugarObjects/templates/person/metadata/metafiles.php
  include/SugarObjects/templates/person/metadata/subpaneldefs.php
  include/SugarObjects/templates/sale/metadata/metafiles.php
  include/SugarObjects/templates/sale/metadata/subpaneldefs.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge
