Repository SuiteCRM/SuiteCRM, pull requests merged in 2022-12, with the labels that each got.

#9802 fix #9802 - Diagnostic checkboxes
  modules/Administration/Diagnostic.tpl
Labels: Status:Assessed, Branch:Hotfix, Hacktoberfest

#9718 Fix #9717 - Security Suite Record Group selector doesn't appear when duplicating records
  include/EditView/EditView2.php
Labels: Status:Assessed, Branch:Hotfix

#9648 Fix #9646 - Display TinyMCE in step 4 of the campaigns form wizard
  include/SugarTinyMCE.php
Labels: Status:Assessed, Branch:Hotfix

#9643 Fix #9574 - Update method to static for module renaming
  modules/Studio/parsers/StudioParser.php
Labels: Status:Assessed, Branch:Hotfix

#9500 Fix #9499 - Add View Survey Responses Menu item
  modules/Surveys/Menu.php
Labels: Status:Assessed, Branch:Hotfix

#9638 Fix Elasticsearch indexing and searching using accented characters
  lib/Search/ElasticSearch/ElasticSearchEngine.php
  lib/Search/SearchQuery.php
  lib/Search/UI/SearchResultsController.php
  lib/Utility/ArrayMapper.php
Labels: Status:Assessed, Branch:Hotfix

#9474 Fix #9473 - Missing item "Survey" in campainglog_activity_type_dom
  include/language/en_us.lang.php
Labels: Status:Assessed, Branch:Hotfix

#9786 Clear caches used by Inline Edition
  modules/Administration/QuickRepairAndRebuild.php
Labels: Status:Assessed, Branch:Hotfix, Hacktoberfest, Hacktoberfest-Accepted

#9671 Fix #9670 - Disabling the user profile option about notification of assignments does not work
  modules/Users/tpls/EditViewFooter.tpl
Labels: Status:Assessed, Branch:Hotfix

#9813 FIX #9344 Error in Browsers console after adding tabs to Quickcreate: function selectTabOnError
  themes/SuiteP/include/DetailView/DetailView.tpl
Labels: Status: Requires Code Review, Branch:Hotfix
