Repository SuiteCRM/SuiteCRM, pull requests merged in 2022-01, with the labels that each got.

#9409 Fixed #9408 - Emails can't be deleted from inline edit
  include/InlineEditing/InlineEditing.php
Labels: Status:Assessed, Branch:Hotfix-7.10.x

#9410 Fix #9378 - Filter by Email1 Field Through the API
  Api/V8/Service/ModuleService.php
Labels: Status:Assessed

#9353 Primary Email property is kept after adding an Email address field
  include/SugarEmailAddress/SugarEmailAddress.js
  jssource/src_files/include/SugarEmailAddress/SugarEmailAddress.js
Labels: Status:Assessed, Branch:Hotfix-7.10.x

#9401 Fix issue #9380 where date action in workflow fails to save
  modules/AOW_WorkFlow/aow_utils.php
Labels: Status:Assessed, Branch:Hotfix

#9407 Fixed #9406 - Validation displayed static message isn't correct
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
Labels: Status:Assessed, Branch:Hotfix-7.10.x

#9398 Core Fix: Consistently store dropdowns in $app_list_strings
  modules/ModuleBuilder/parsers/parser.dropdown.php
  modules/Studio/DropDowns/DropDownHelper.php
Labels: Status:Assessed, Branch:Hotfix-7.10.x

#9312 Declaring object within StudioClass to remove Strict Warnings
  modules/ModuleBuilder/views/view.modulefields.php
Labels: Status:Assessed, Branch:Hotfix

#9420 Fix #8525 #8309 Bulk Action button missing and delete button showing for users with no delete access
  include/ListView/ListViewDisplay.php
Labels: Status:Assessed

#8428 FIXED #8155 - Unused PDF Settings
  modules/Configurator/language/en_us.lang.php
Labels: Status:Assessed
