Repository SuiteCRM/SuiteCRM, pull requests merged in 2023-06, with the labels that each got.

#10057 Fix #10056: User bean value is_admin is unset on save()
  include/utils.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10050 Add missing language definitions for the module loader
  modules/Administration/language/en_us.lang.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#9983 Fix issue #9516
  lib/Search/SearchResults.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9816 Fix #9816 - $item is an array, no object
  include/SugarFolders/SugarFolders.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9657 Fix #9654 - Fix issue with different date formats being compared for change log
  include/database/DBManager.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10051 Add better description of what is being removed during module installation for ACLs
  modules/ACL/remove_actions.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10036 Fix #10033 PHP Fatal error Uncaught TypeError PHP8
  modules/AOW_Actions/actions/actionSendEmail.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10055 Fix #9548 - Wrong decimal precision returned in a Modify Record workflow action
  modules/AOW_WorkFlow/aow_utils.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#8683 Fix #8682 - Workflow fails with relationship condition
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10024 Fix #9601 - Fix bug where report conditions parenthesis pairs would not save correctly.
  modules/AOR_Conditions/AOR_Condition.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#9938 Fix #9937 - Resolve high memory usage when performing bulk relationship changes
  data/Link2.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing
