Repository SuiteCRM/SuiteCRM, pull requests merged in 2023-04, with the labels that each got.

#9642 Fix #9602 - ProspectLists save function has a duplication issue
  modules/ProspectLists/Save.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9903 Fix #9902 - Workflow - Some Date calculations fail with certain formats
  modules/AOW_Actions/FormulaCalculator.php
Labels: Status:Assessed, Area: Workflow, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9876 Fix #9875 SugarFeed shows 0 seconds ago and negative interval for cer…
  modules/SugarFeed/SugarFeed.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9849 allowed_preview is defined twice in the array
  include/utils.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9828 Fix #9828 - $mod_strings not in scope for line 395 of the same file
  modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9817 Fix #9817 - Typo
  modules/CampaignTrackers/DetailView.html
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9812 decimal numbers calculations fix
  modules/AOW_Actions/actions/actionComputeField.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9787 #9780 New User Group Popup. Popup does not show after creating a user
  include/javascript/sugar_3.js
  jssource/src_files/include/javascript/sugar_3.js
Labels: Status:Requires Updates, Status:Assessed, Branch:Hotfix, Hacktoberfest, Status: Passed Code Review, Status: Passed Testing

#9784 Fix #9783 - Compose view quick search for email templates
  include/TemplateHandler/TemplateHandler.php
  include/javascript/EmailsComposeViewModal.js
  jssource/src_files/include/javascript/EmailsComposeViewModal.js
  modules/Emails/include/ComposeView/ComposeView.tpl
  modules/Emails/include/ComposeView/EmailsComposeView.js
Labels: Status:Assessed, Branch:Hotfix, Hacktoberfest, Status: Passed Code Review, Status: Passed Testing

#9777 Fix #9768 - Do not convert link URLs in TinyMCE
  include/SuiteEditor/SuiteEditorConnector.php
  modules/Emails/include/ComposeView/EmailsComposeView.js
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9765 Fix #9764 - Add extra To addresses to CC field
  modules/Emails/EmailsController.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9622 Fix #9621 - Workflows Calculate Field Actions don't translate dynamicenum fields
  modules/AOW_Actions/actions/actionComputeField.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9542 Fix php 8 issue with old user preferences null values
  modules/Charts/Dashlets/MyPipelineBySalesStageDashlet/MyPipelineBySalesStageDashlet.php
  modules/Charts/Dashlets/OpportunitiesByLeadSourceByOutcomeDashlet/OpportunitiesByLeadSourceByOutcomeDashlet.php
  modules/Charts/Dashlets/OpportunitiesByLeadSourceDashlet/OpportunitiesByLeadSourceDashlet.php
  modules/Charts/Dashlets/OutcomeByMonthDashlet/OutcomeByMonthDashlet.php
  modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9520 Fix #9326 - Adding decimal and float case option for export to use user-defined…
  include/export_utils.php
Labels: Status: Requires Code Review, Status:Assessed, Branch:Hotfix, Status: Passed Testing

#9471 Fix #9470 - Set fdow in Calendar popup date selector for range search and MassUpdate
  include/MassUpdate.php
  include/SugarFields/Fields/Datetimecombo/RangeSearchForm.tpl
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9329 Fix #8897 - Adding missing relationship for SurveyResponses module
  modules/SurveyResponses/vardefs.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9325 Fix #9153 - Adding dynamicenum case option for export
  include/export_utils.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9965 Fix broken Api authentication under PHP 8.0 - upgrade league/oauth2-server to latest version
  Api/V8/Config/services/middlewares.php
  Api/V8/OAuth2/Entity/ClientEntity.php
  Api/V8/OAuth2/Repository/ClientRepository.php
  composer.json
  composer.lock
  lib/API/OAuth2/Entities/ClientEntity.php
  lib/API/OAuth2/Repositories/ClientRepository.php
  modules/OAuth2Clients/OAuth2Clients.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing
