Repository SuiteCRM/SuiteCRM, pull requests merged in 2023-10, with the labels that each got.

#10212 Fix #10199 - PHP Fatal error: Uncaught Error: Non-static method Sug…
  include/generic/SugarWidgets/SugarWidgetFieldname.php
Labels: Status:Assessed, Area: Dashlets, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10206 Fix #10205. Compatibility hotfix for PHP 8 in ActivitiesRelationship.php
  modules/ModuleBuilder/parsers/relationships/ActivitiesRelationship.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10201 Fix #9950 editing Email settings drops TLS SSL selection
  include/utils.php
Labels: Status:Assessed, Area: Emails:Config, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10160 Fix #10159 - Accounts - Not able to search by fax on 'Any Phone' search field
  modules/Accounts/metadata/SearchFields.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Accounts

#10143 Update ready.php change checking of upload max filesize from > to >=
  install/ready.php
Labels: Status:Assessed, Area: Environment, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10142 Fix #10141 - Orphaned Case Attachments bug
  modules/AOP_Case_Updates/Case_Updates.php
Labels: Status:Assessed, Area: Cases, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10122 Fix 10115 - Wokflow Calculate Action broken under PHP8
  modules/AOW_WorkFlow/controller.php
Labels: Status:Assessed, Area: Workflow, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10114 Fix parameter userTime method in class TimeDate
  include/TimeDate.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10049 Relationship::delete expects a string (the name of the relationship)
  data/SugarBean.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Relationships

#10027 Respect wildcard in front when searching a full name in basic search
  include/SearchForm/SearchForm2.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 9-14, Area:Search

#9964 Fix #8980 - Check beanFiles for class path
  download.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, Area:Documents

#9881 Fix #9880 - Error when importing currency fields with a decimal separator
  include/SugarFields/Fields/Currency/SugarFieldCurrency.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, Area:Import

#9459 Fix #9456 - choose email provider does not populate SMTP settings
  modules/OutboundEmailAccounts/smtpPreselection.tpl
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#9413 Fix #9412 - Wrong email value displayed when aborting an inline edition
  include/InlineEditing/inlineEditing.js
Labels: Status:Assessed, Area: Clean Up: Performance, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10028 Allow workflow to send plain text emails
  modules/AOW_Actions/actions/actionSendEmail.php
Labels: Status:Assessed, Area: Workflow, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10253 Fix #10252 Google Maps Geocoded Counts not displaying properly
  modules/jjwg_Maps/controller.php
Labels: Status:Assessed, Branch:Hotfix, Hacktoberfest, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10248 Fix #9537 Activity subpanel isn't working in a module with a parent_t…
  data/Relationships/One2MBeanRelationship.php
Labels: Status:Assessed, Branch:Hotfix, Hacktoberfest, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10241 Fix #9898 Invalid cookie domain when using non-standard HTTP Port.
  include/MVC/SugarApplication.php
Labels: Status:Assessed, Area: Environment, Branch:Hotfix, Hacktoberfest, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#9522 Fix #9435 - Dropdown doesn't return empty selected value
  modules/AOW_WorkFlow/aow_utils.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing
