Repository SuiteCRM/SuiteCRM, pull requests merged in 2023-09, with the labels that each got.

#9941 Fix #9941 - Remove sugar pro flavor
  include/SugarFields/Parsers/DetailViewMetaParser.php
  include/SugarFields/Parsers/MetaParser.php
  modules/ModuleBuilder/MB/MBPackage.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#9726 Fix #9725 - Date field value isn't saved in a Workflow action related module
  modules/AOW_Actions/AOW_Action.php
Labels: Status:Requires Updates, Status:Assessed, Area: Workflow, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10185 Fix #10184 - Timezone not set on silent install
  modules/Users/User.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10140 Fix #10139 - HTML Text Field tinyMCE version
  include/SugarFields/Fields/Text/SugarFieldText.php
Labels: Status:Assessed, Area: Cases, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10132 Fix #10131 - Fix issue with file mode changes not being applied on cache rebuild
  include/utils/sugar_file_utils.php
Labels: Status:Assessed, Area: Environment, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10110 Implements displayParams.initial_filter to Parent field
  include/SugarFields/Fields/Parent/EditView.tpl
  include/SugarFields/Fields/Parent/SearchView.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#9996 Fix #8939 - Fix Static call to non-static method in AOW_WorkFlow
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Status:Assessed, Area: Workflow, Status: Passed Code Review, Status: Passed Testing

#9999 Fix #9021 - User Preferences Wrong Label.
  themes/SuiteP/modules/Users/tpls/DetailView-advanced-tab-content.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, Area:Users

#10020 Fix #10020 - Issue with missing label on Contact Module
  modules/Contacts/language/en_us.lang.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, Area:Contacts

#10058 Fix #5390 - Redundant message when duplicating a survey
  modules/Surveys/Lines/Lines.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, Area:Surveys

#9994 Fix #9148- Fix missing sorting labels.
  modules/Project/language/en_us.lang.php
  modules/ProjectTask/language/en_us.lang.php
  modules/ProspectLists/language/en_us.lang.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, Area:Projects

#9997 Fix #8359 - Fix Contract renewal reminder title is hardcoded.
  modules/AOS_Contracts/AOS_Contracts.php
  modules/AOS_Contracts/language/en_us.lang.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10079 Fix #3050 - AOW: dropdown lists is not updating (calclulate field & modified record action)
  modules/AOW_Actions/actionLines.js
Labels: Status:Assessed, Area: Workflow, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10063 Fix #2111 - Hover over favorites item, shows module name, not label
  themes/SuiteP/tpls/_headerModuleList.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, Area:Themes

#10060 Fix #10060 - User preferences detail-view template issues.
  themes/SuiteP/modules/Users/tpls/DetailView-advanced-tab-content.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, Area:Users

#10130 Fix #10129 Fix issue with step 2 & 3 on the importer failing
  modules/Import/sources/ImportFile.php
  modules/Import/views/view.confirm.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Import

#10102 Fix #5385 - Fix Closed survey issues
  modules/Surveys/Entry/Survey.php
  modules/Surveys/language/en_us.lang.php
  modules/Surveys/tpls/closeSurvey.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Surveys

#10092 Fix #9062 - Studio layout changes not being reflected
  modules/ModuleBuilder/parsers/ModuleBuilderParser.php
  modules/ModuleBuilder/parsers/parser.label.php
  modules/ModuleBuilder/parsers/relationships/AbstractRelationships.php
  modules/ModuleBuilder/parsers/views/DashletMetaDataParser.php
Labels: Status:Assessed, Area: Studio, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10064 Fix #3842 - Vertical scrollbar missing in Studio>Module>Layouts>
  themes/SuiteP/css/suitep-base/studio.scss
Labels: Status:Assessed, Area: Studio, Status: Passed Code Review, Status: Passed Testing

#10008 Fix #10007 - Text area cannot span two fields
  themes/SuiteP/css/suitep-base/editview.scss
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing
