Repository SuiteCRM/SuiteCRM, pull requests merged in 2023-02, with the labels that each got.

#9666 Fix #9665 - Set unique id for "Reset module" button in studio
  modules/ModuleBuilder/language/en_us.lang.php
  modules/ModuleBuilder/views/view.wizard.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#9742 Closing count bracket before relational operator PHP 8.0 count throwing TypeError
  include/ListView/ListViewData.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9751 Fix #9750 - Receive related parameters of type dynamicenum in workflow formulas
  modules/AOW_Actions/actions/actionComputeField.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#9796 Fix #4646 - Hard coded messages in Surveys module
  modules/SurveyResponses/language/en_us.lang.php
  modules/SurveyResponses/tpls/detailquestionresponses.tpl
  modules/Surveys/javascript/Survey.js
  modules/Surveys/language/en_us.lang.php
  modules/Surveys/tpls/detailsurveyquestions.tpl
  modules/Surveys/tpls/editsurveyquestions.tpl
  modules/Surveys/tpls/reports.tpl
  modules/Surveys/vardefs.php
  modules/Surveys/views/view.reports.php
Labels: Status: Ready to Merge, Hacktoberfest, Status: Passed Code Review, Status: Passed Testing

#9836 Fix #9835 - Case Updates save bug
  modules/AOP_Case_Updates/Case_Updates.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#9874 Fix #9873 - Plesk php.ini disable_functions = opcache_get_status
  include/SugarCache/SugarCache.php
  include/utils/file_utils.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#9872 Fix #9871 - Javascript message error when bulk updating all user records
  modules/Users/language/en_us.lang.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9884 Fix #9883 - Security Groups do not work with modules whose name exceeds 36 characters.
  metadata/securitygroups_recordsMetaData.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9910 Fix #9909 - Default empty item when creating a new Dropdown field
  modules/DynamicFields/templates/Fields/Forms/dynamicenum.php
  modules/DynamicFields/templates/Fields/Forms/enum2.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9914 Fix #9914 - Update dashboard.scss for dashlet options overflow
  themes/SuiteP/css/suitep-base/dashboard.scss
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9955 Fix #9926 - Add missing check on product image upload
  modules/AOS_Products/AOS_Products.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#9954 Fix Campaigns parenthesis
  modules/Campaigns/CampaignDiagnostic.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#9901 Fix #9900 - Conditions doesn't recognize some of the characters set
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing
