Repository SuiteCRM/SuiteCRM, pull requests merged in 2024-01, with the labels that each got.

#10265 Fix #5392 - My Filters doesn`t show up on Project Tasks
  modules/ProjectTask/views/view.list.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10266 Fix #9563 - HTML Type field doesn't populate
  include/SugarFields/Fields/Html/DetailView.tpl
Labels: Status: Passed Code Review, Status: Passed Testing

#10271 Fix #373 [SuiteCRM 8]Google API Token for calendar sync in User Profi…
  modules/Users/tpls/EditViewFooter.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10295 Fix #10242 - Mass Security Group Assignment fails when multiple items…
  modules/SecurityGroups/AssignGroups.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10296 Fix #10296 - Add duplication logic check on run_when Always
  modules/AOW_WorkFlow/AOW_WorkFlow.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10297 Fix #9453 - User 'delete' option missing from menu
  modules/Users/controller.php
  modules/Users/language/en_us.lang.php
  modules/Users/views/view.detail.php
  themes/SuiteP/modules/Users/tpls/DetailView.tpl
Labels: Status: Passed Code Review, Status: Passed Testing

#10313 Remove unused line in repair
  modules/Administration/RepairFieldCasing.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10294 Fix #9144 - Popup error messages
  modules/ProspectLists/Delete.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10292 Fix #2833 - Process Audit Advanced Search
  include/SugarFields/Fields/Parent/SearchView.tpl
  modules/AOW_Processed/vardefs.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10278 Fix #6397 - Studio: Reset Module: Remove Custom Fields
  modules/DynamicFields/templates/Fields/TemplateHTML.php
  modules/DynamicFields/templates/Fields/TemplateParent.php
  modules/DynamicFields/templates/Fields/TemplateRelatedTextField.php
  modules/ModuleBuilder/tpls/resetModule.tpl
  modules/ModuleBuilder/views/view.resetmodule.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10314 Fix #10314 - disabling active languages
  modules/Administration/controller.php
  modules/Administration/language/en_us.lang.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10308 Fix #10307 retrieve object name via beanfactory
  include/TemplateHandler/TemplateHandler.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10311 Fix #10310 Survey reports ui improvements
  modules/Surveys/tpls/Reports/checkbox.tpl
  modules/Surveys/tpls/Reports/matrix.tpl
  modules/Surveys/tpls/Reports/option.tpl
  modules/Surveys/tpls/reports.tpl
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10275 Fix #10207 #10209 - Multiple Elasticsearch indexing issues
  data/SugarBean.php
  include/Smarty/plugins/function.diff_for_humans.php
  lib/Search/ElasticSearch/ElasticSearchIndexer.php
  lib/Search/Index/IndexingSchedulerTrait.php
  lib/Search/UI/SearchThrowableHandler.php
  modules/Administration/Search/ElasticSearch/Controller.php
  modules/Administration/Search/ElasticSearch/scripts.js
  modules/Administration/Search/ElasticSearch/view.tpl
  modules/Administration/language/en_us.lang.php
  modules/Home/language/en_us.lang.php
  modules/Schedulers/Scheduler.php
  modules/Schedulers/_AddJobsHere.php
  modules/Schedulers/language/en_us.lang.php
Labels: Status:Assessed, Area: Elasticsearch, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8
