Repository SuiteCRM/SuiteCRM, pull requests merged in 2024-10, with the labels that each got.

#10525 Fix #5287 - Change secret field is too short
  themes/SuiteP/css/suitep-base/editview.scss
  themes/SuiteP/css/suitep-base/forms.scss
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10520 Fix #10520 - Discount Calculation incorrect when changing Currency
  modules/Currencies/ListCurrency.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10518 Fix #8332 - Recipient Type [Language]
  modules/Emails/language/en_us.lang.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10517 Fix #507 - Workflows - Calculated Fields - related field won't show up as parameter
  modules/AOW_Actions/actions/actionComputeField.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10516 Fix #10445 - Calendar: Calls still show even using Settings: 'Show Calls' = NO
  modules/Calendar/CalendarActivity.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10495 Fix #9261 - Use decimal symbol configured in system and user
  include/utils.php
  modules/AOS_PDF_Templates/templateParser.php
  modules/EmailTemplates/EmailTemplateParser.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10489 Fix #10488 - Expand the number of filters in message queue views
  modules/EmailMan/metadata/SearchFields.php
  modules/EmailMan/metadata/listviewdefs.php
  modules/EmailMan/metadata/searchdefs.php
  modules/EmailMan/vardefs.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10455 Add scrollbars for Toolbox and Layout | Studio
  themes/SuiteP/css/suitep-base/studio.scss
Labels: Status:Assessed, Area: Studio, Area: Styling, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10451 Fix #10450 - Add check for empty value before searching array
  ModuleInstall/ModuleInstaller.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10288 Fix #9737 - Fix issue with campaigns displaying a blank email template
  include/SuiteEditor/SuiteEditorConnector.php
  modules/Campaigns/WizardMarketing.html
Labels: Status:Assessed, Area: Emails:Campaigns, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10225 Fix #9036 - change log level according it message
  data/Relationships/M2MRelationship.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10101 #10099 Workflow action create record by Scheduler set incorrect date field values from related entity
  modules/AOW_Actions/actions/actionCreateRecord.php
Labels: Status:Assessed, Area: Workflow, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10523 Fix #10503 - Item label in dropdown list is not displayed if it contains '<' character
  include/HtmlSanitizer.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10557 Fix #10421 - Studio | Layout Editor CSS broken
  modules/ModuleBuilder/javascript/studio2.js
Labels: Status:Assessed, Area: Studio, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8
