Repository SuiteCRM/SuiteCRM, pull requests merged in 2024-07, with the labels that each got.

#10469 Fix #9177 - Cant use edit inline in UserType field
  modules/Users/User.php
  modules/Users/vardefs.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10461 Fix #10268 - Access token wil not refresh for Oauth2 password clients
  Api/V8/OAuth2/Repository/ClientRepository.php
  lib/API/OAuth2/Repositories/ClientRepository.php
Labels: Status:Assessed, Status: Passed Code Review, Status: Passed Testing

#10444 Fix #10443 - Incorrect lengths in emails_text vardefs
  metadata/emails_beansMetaData.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10442 Fix #10437 - Calendar - 'Today' left-hand side bar option loads the week
  modules/Calendar/Calendar.php
  modules/Calendar/Menu.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10429 Fix #5653 - VAT Display in PDF Templates wrong when Currency Significant Digits set to 0
  modules/AOS_PDF_Templates/templateParser.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10399 Fix #2175 - No gif and shifted text after saving task in gants view
  modules/Project/js/main_lib.js
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10394 Fix #2828 - Not translatable messages in Dashlet parameters
  include/javascript/sugar_3.js
  include/language/en_us.lang.php
  jssource/src_files/include/javascript/sugar_3.js
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10390 Fix #10390 - URL is not clickable
  modules/AOS_Products/metadata/detailviewdefs.php
  modules/AOS_Products/vardefs.php
Labels: Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing

#10380 Fix #7150 - Show subpanels correctly
  modules/Campaigns/SubPanelViewer.php
Labels: Status:Assessed, Area: Campaigns, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10362 Fix #9078 - Favorites adds record twice to the sidebar and to the db
  include/MVC/View/SugarView.php
  modules/Favorites/favorites.js
  modules/Favorites/language/en_us.lang.php
  modules/Spots/views/view.edit.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10341 Fix #10339 - Inconsistent application of trim function on name & varchar fields
  data/SugarBean.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10336 Fix #10335 - Incorrect codification in the names of events displayed in the Calendar
  modules/Calendar/Calendar.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10320 #10319 fix(JSON API v1) - SQL error when filtering by custom fields
  Api/V8/BeanDecorator/BeanManager.php
Labels: Status:Assessed, Area: API, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10315 More logical code structure, don't need to fill variable if gets over…
  modules/InboundEmail/InboundEmail.php
Labels: Status:Assessed, Area: Clean Up, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10441 Fix # - VAT Values display incorrectly on Quotes->Service Line Items, if Significant Figures = 0
  modules/AOS_Products_Quotes/Line_Items.php
Labels: Status: Passed Code Review, Status: Passed Testing
