Repository SuiteCRM/SuiteCRM, pull requests merged in 2024-05, with the labels that each got.

#10411 Fix #10410 - Check report has been loaded before setting user params
  modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#9896 Fix #9895 - Workflow - Copying Formatted values of a multienum to another field
  modules/AOW_Actions/actions/actionComputeField.php
Labels: Status:Assessed, Area: Workflow, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#9988 Fix issue #9985
  modules/Calls/Call.php
Labels: Status:In Review, Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10186 Fix #10182 - Graphic Issue search view after 7.14 upgrade
  lib/Search/UI/SearchFormView.php
Labels: Status:Assessed, Area: Styling, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#9972 Fix #9971 - Workflow - Add filters to quick and advanced search view in AOW Processed module
  modules/AOW_Processed/metadata/searchdefs.php
Labels: Status:Assessed, Area: Workflow, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10322 Fix# 10321 Creation of Project with Template Causes 500 Error
  modules/Project/Project.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Projects

#10328 Fix #10327 - Survey Responses doesn't get assigned_user after sending Survey
  modules/Surveys/Entry/SurveySubmit.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Surveys

#10375 Fix #10375 - Upgradewizard double commit
  modules/UpgradeWizard/index.php
Labels: Status:Assessed, Area: Clean Up: Performance, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10409 fix skip to last page if disable_count_query=true
  data/SugarBean.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10323 Fix #10172 Emails don't show subject MIME headers #10269 Email sync …
  modules/InboundEmail/InboundEmail.php
Labels: Status:Assessed, Area: Emails, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing

#10424 Fix #9213 - $discount_amount corrupted
  modules/AOS_PDF_Templates/templateParser.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10389 Fix #1872 - Admin - Install Module - "Back to Module Loader" shows page with header only
  modules/Administration/UpgradeHistory.php
Labels: Status: Passed Code Review, Status: Passed Testing

#10426 Feature #10426 - new issue menu templates
  .github/ISSUE_TEMPLATE/01_issueTemplate.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/SECURITY.md
  .github/workflows/add-comment.yml
Labels: Status: Requires Testing, Status: Passed Code Review
