Repository SuiteCRM/SuiteCRM, pull requests merged in 2025-05, with the labels that each got.

#10309 Fix #10264 Error Assigned_user_name SearchView.tpl (`{php}` tag now crashes Smarty 4)
  include/SearchForm/SearchForm2.php
  include/SugarFields/Fields/Assigned_user_name/SearchView.tpl
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10649 Fix #8280 - Fix Autocomplete search in line items
  themes/SuiteP/css/suitep-base/yui.scss
Labels: Status:Assessed, Area: Styling, Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10612 Fix - #10611 Subpanels don't show related records links when view permission is set to "group"
  include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php
Labels: Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10607 Fix #10606 - Recently viewed items tooltip shows module name instead of full record name
  themes/SuiteP/tpls/_headerModuleList.tpl
Labels: Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10625 Fix #10624 - Prevent Multiple Submissions on Survey Forms
  modules/Surveys/Entry/Survey.php
Labels: Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10538 Fix #10243 - studio not saving field properties correctly
  modules/ModuleBuilder/parsers/StandardField.php
Labels: Status:Assessed, Area: Studio, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10285 Fix non-countable error when importing CSV
  modules/Import/views/ImportListView.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Import

#10617 Fix #10616 - Default values of DateTime always in English and value “first day of next month” gives an error
  modules/DynamicFields/templates/Fields/TemplateDatetimecombo.php
Labels: Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10648 Fix #8632 - API V8 /meta/fields/{moduleName} endpoint output without field labels
  Api/V8/Service/MetaService.php
Labels: Status:Assessed, Area: API, Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10623 Allow End Users to use the PATCH method for the V8 API
  Api/Core/app.php
Labels: Status: Passed Code Review, Status: Passed Testing, PR 1-3

#10544 Fix #10543 - Remove Security Groups button on subpanelsbased on EditView
  include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8
