Repository SuiteCRM/SuiteCRM, pull requests merged in 2025-03, with the labels that each got.

#10565 Fix #10564 - Thank you message in Surveys only in English
  modules/Surveys/Entry/Thanks.php
  modules/Surveys/language/en_us.lang.php
Labels: Status:Assessed, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Surveys

#10502 Remove duplicate line
  modules/AOR_Charts/AOR_Chart.php
Labels: Status:Assessed, Area: Clean Up, Branch:Hotfix, Status: Ready to Merge, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10480 Fix #10479 - Call LoggerManager's warn() method instead of warning()
  cron.php
  modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8

#10400 Correctly find the id of related objects in search results
  lib/Search/SearchResults.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing, PR 4-8, Area:Search

#9810 Fix #9809 - Incorrect parsing of 0 values in PDF templates
  modules/AOS_PDF_Templates/templateParser.php
Labels: Status:Assessed, Branch:Hotfix, Status: Passed Code Review, Status: Passed Testing
